const OS = 'https://molochdagod.github.io/ObjectStore/';

export const SHADOW_KNIGHTS_SPEC = {
  meta: {
    id: 'shadow-knights',
    gameName: 'Shadow Knights',
    studioName: 'Grudge Studios',
    tagline: 'Where Darkness Forges Champions',
    version: '1.0.0',
    theme: 'dark-medieval-fantasy',
    setting: 'The shattered kingdom of Valtheris, where the Duskfall — a cataclysm of shadow energy — split reality into three overlapping planes: the Mortal Realm, the Umbral Veil, and the Ember Core. Knights who survived the Duskfall gained the ability to channel shadow and ember magic, becoming Shadow Knights.',
    artStyle: 'pixel',
    colorPalette: {
      primary: '#8b5cf6',
      secondary: '#dc2626',
      accent: '#f59e0b',
      danger: '#ef4444',
      background: '#0a0510',
      text: '#e2e8f0',
    },
    fonts: { heading: 'Cinzel', body: 'Jost' },
    currency: { name: 'Dark Marks', icon: 'coin', plural: 'Dark Marks' },
    resources: [
      { name: 'Shadow Essence', icon: 'gem', description: 'Condensed darkness harvested from Umbral fissures' },
      { name: 'Ember Shards', icon: 'ore', description: 'Crystallized fire from the Ember Core' },
      { name: 'Soul Iron', icon: 'ingot', description: 'Metal forged in spectral furnaces' },
      { name: 'Veil Dust', icon: 'herb', description: 'Residue from torn planar boundaries' },
    ],
    objectStoreBase: OS,
    battleBackgrounds: [
      '/backgrounds/factory/shadow-knights/shadow_ruins.png',
      '/backgrounds/factory/shadow-knights/ember_forge.png',
      '/backgrounds/factory/shadow-knights/umbral_forest.png',
      '/backgrounds/factory/shadow-knights/crystal_cavern.png',
      '/backgrounds/factory/shadow-knights/duskfall_nexus.png',
    ],
  },

  raceCount: 6,
  classCount: 4,
  attributeCount: 8,
  enemyCount: 24,
  bossCount: 4,
  locationCount: 20,
  chapterCount: 6,
  skillTierCount: 4,
  equipmentTierCount: 8,

  races: [
    {
      id: 'ironborn',
      name: 'Ironborn',
      icon: `${OS}icons/rpg_splash/rpg_splash_1.png`,
      color: '#94a3b8',
      description: 'Resilient humans forged by war and shadow, masters of adaptation.',
      lore: 'The Ironborn are descendants of the original Knights of Valtheris. When the Duskfall struck, their iron discipline allowed them to resist madness. They serve as the backbone of the resistance.',
      bonuses: { Strength: 1, Vitality: 1, Endurance: 1, Dexterity: 1, Agility: 1, Intellect: 1, Wisdom: 1, Tactics: 1 },
      passive: '+1 to all attributes',
      trait: 'Adaptable',
      traitDescription: 'Ironborn gain a small bonus to all stats, making them effective in any role.',
    },
    {
      id: 'duskelf',
      name: 'Dusk Elf',
      icon: `${OS}icons/rpg_splash/rpg_splash_5.png`,
      color: '#a855f7',
      description: 'Elves corrupted by shadow magic, wielding darkness as a weapon.',
      lore: 'Once creatures of pure light, the Dusk Elves embraced the Umbral Veil during the cataclysm. Their bodies shimmer between planes, granting them unnatural agility and arcane sight.',
      bonuses: { Intellect: 3, Agility: 3, Wisdom: 2 },
      passive: '+3 INT, +3 AGI, +2 WIS',
      trait: 'Shadowmeld',
      traitDescription: '15% chance to dodge attacks by phasing into the Umbral Veil.',
    },
    {
      id: 'emberdwarf',
      name: 'Ember Dwarf',
      icon: `${OS}icons/rpg_splash/rpg_splash_12.png`,
      color: '#f97316',
      description: 'Dwarves infused with the Ember Core\'s fire, forging weapons of living flame.',
      lore: 'When the Ember Core erupted, some dwarven clans were bathed in its primal fire. Rather than perishing, they absorbed it. Now their veins glow with molten light.',
      bonuses: { Strength: 3, Vitality: 3, Endurance: 2 },
      passive: '+3 STR, +3 VIT, +2 END',
      trait: 'Forge Blood',
      traitDescription: 'Ember Dwarves deal +10% fire damage and resist 15% fire damage.',
    },
    {
      id: 'wraithkin',
      name: 'Wraithkin',
      icon: `${OS}icons/rpg_splash/rpg_splash_18.png`,
      color: '#22d3ee',
      description: 'Spectral beings trapped between life and death, wielding soul magic.',
      lore: 'Wraithkin are souls that refused to pass into the Umbral Veil. They anchor themselves to reality through sheer willpower, existing as luminous shades with terrifying magical potential.',
      bonuses: { Intellect: 4, Wisdom: 3, Tactics: 1 },
      passive: '+4 INT, +3 WIS, +1 TAC',
      trait: 'Soul Anchor',
      traitDescription: 'Upon death, Wraithkin have a 20% chance to revive at 15% HP once per battle.',
    },
    {
      id: 'beastblood',
      name: 'Beastblood',
      icon: `${OS}icons/rpg_splash/rpg_splash_25.png`,
      color: '#65a30d',
      description: 'Savage half-beasts who channel primal fury in combat.',
      lore: 'The Duskfall warped some warriors into lycanthropic hybrids. The Beastblood embrace their curse, channeling feral rage into devastating combat prowess.',
      bonuses: { Strength: 4, Agility: 2, Dexterity: 2 },
      passive: '+4 STR, +2 AGI, +2 DEX',
      trait: 'Bloodrage',
      traitDescription: 'Below 30% HP, Beastblood gain +25% attack speed and +15% damage.',
    },
    {
      id: 'crystalborn',
      name: 'Crystalborn',
      icon: `${OS}icons/rpg_splash/rpg_splash_30.png`,
      color: '#06b6d4',
      description: 'Living crystal warriors grown from the Ember Core\'s mineral veins.',
      lore: 'Born from the collision of shadow and ember energy, Crystalborn are sentient mineral formations that absorbed both magical frequencies. Their crystalline bodies are nearly indestructible.',
      bonuses: { Vitality: 4, Endurance: 3, Tactics: 1 },
      passive: '+4 VIT, +3 END, +1 TAC',
      trait: 'Crystal Shell',
      traitDescription: 'Crystalborn start battles with a shield absorbing 10% of their max HP.',
    },
  ],

  classes: [
    {
      id: 'shadowblade',
      name: 'Shadowblade',
      icon: `${OS}icons/skill_nobg/Archerskill_01_nobg.png`,
      color: '#8b5cf6',
      description: 'Swift assassins who strike from the Umbral Veil.',
      lore: 'Shadowblades learned to weaponize the Duskfall itself. They phase between reality and shadow, delivering lethal strikes before vanishing back into darkness.',
      role: 'DPS/Assassin',
      startingAttributes: { Strength: 6, Vitality: 4, Endurance: 3, Dexterity: 8, Agility: 7, Intellect: 4, Wisdom: 3, Tactics: 5 },
      abilities: [
        { id: 'umbral-strike', name: 'Umbral Strike', icon: `${OS}icons/skills/aeromancer_1.png`, description: 'Phase through shadow to strike a target for 1.8x damage.', type: 'physical', damage: 1.8, manaCost: 0, staminaCost: 20, cooldown: 2, target: 'enemy', effect: 'bleed' },
        { id: 'shadow-step', name: 'Shadow Step', icon: `${OS}icons/skills/aeromancer_11.png`, description: 'Teleport behind an enemy and strike for 1.4x, ignoring armor.', type: 'physical', damage: 1.4, manaCost: 10, staminaCost: 15, cooldown: 3, target: 'enemy', effect: null },
        { id: 'veil-dance', name: 'Veil Dance', icon: `${OS}icons/skills/aeromancer_12.png`, description: 'Rapid multi-strike attack hitting 3 times for 0.8x each.', type: 'physical', damage: 0.8, manaCost: 0, staminaCost: 25, cooldown: 4, target: 'enemy', effect: null },
        { id: 'dark-cloak', name: 'Dark Cloak', icon: `${OS}icons/skills/aeromancer_13.png`, description: 'Become invisible for 2 turns, gaining +50% crit chance on next attack.', type: 'buff', damage: 0, manaCost: 15, staminaCost: 10, cooldown: 5, target: 'self', effect: null },
      ],
      signatureAbility: { id: 'phantasm-barrage', name: 'Phantasm Barrage', icon: `${OS}icons/skill_nobg/Archerskill_02_nobg.png`, description: 'Create shadow clones that each attack for 1.2x damage (5 hits total).', type: 'physical', damage: 1.2, manaCost: 30, staminaCost: 30, cooldown: 8, target: 'enemy', effect: 'bleed' },
      transformAbility: { name: 'Void Phantom', description: 'Become a being of pure shadow. All attacks pierce armor, +50% speed, 3 turns.' },
    },
    {
      id: 'emberknight',
      name: 'Ember Knight',
      icon: `${OS}icons/skill_nobg/Archerskill_03_nobg.png`,
      color: '#ef4444',
      description: 'Heavy armored warriors channeling the Ember Core\'s fire.',
      lore: 'Ember Knights are the vanguard of Valtheris, wielding weapons wreathed in living flame. Their ember-forged armor can withstand any blow while their strikes set the battlefield ablaze.',
      role: 'Tank/Frontline DPS',
      startingAttributes: { Strength: 8, Vitality: 7, Endurance: 6, Dexterity: 4, Agility: 3, Intellect: 3, Wisdom: 4, Tactics: 5 },
      abilities: [
        { id: 'flame-cleave', name: 'Flame Cleave', icon: `${OS}icons/skills/berserker_1.png`, description: 'A sweeping fire attack hitting all front-row enemies for 1.5x.', type: 'physical', damage: 1.5, manaCost: 0, staminaCost: 20, cooldown: 2, target: 'enemy', effect: 'burn' },
        { id: 'ember-shield', name: 'Ember Shield', icon: `${OS}icons/skills/berserker_11.png`, description: 'Raise a fire barrier absorbing damage and reflecting 30% as burn.', type: 'buff', damage: 0, manaCost: 10, staminaCost: 15, cooldown: 3, target: 'self', effect: null },
        { id: 'molten-charge', name: 'Molten Charge', icon: `${OS}icons/skills/berserker_12.png`, description: 'Rush forward dealing 2.0x damage and pushing target back one row.', type: 'physical', damage: 2.0, manaCost: 0, staminaCost: 30, cooldown: 4, target: 'enemy', effect: 'stun' },
        { id: 'guardian-oath', name: 'Guardian Oath', icon: `${OS}icons/skills/berserker_13.png`, description: 'Intercept attacks aimed at allies for 3 turns, taking 25% less damage.', type: 'buff', damage: 0, manaCost: 5, staminaCost: 20, cooldown: 5, target: 'self', effect: null },
      ],
      signatureAbility: { id: 'inferno-judgement', name: 'Inferno Judgement', icon: `${OS}icons/skill_nobg/Archerskill_04_nobg.png`, description: 'Call down a pillar of ember fire dealing 3.0x damage and burning all enemies for 3 turns.', type: 'physical', damage: 3.0, manaCost: 20, staminaCost: 35, cooldown: 8, target: 'all_enemies', effect: 'burn' },
      transformAbility: { name: 'Ember Colossus', description: 'Grow into an ember giant. +100% HP, +50% damage, fire aura damages nearby enemies, 3 turns.' },
    },
    {
      id: 'veilweaver',
      name: 'Veil Weaver',
      icon: `${OS}icons/skill_nobg/Archerskill_05_nobg.png`,
      color: '#06b6d4',
      description: 'Mystics who manipulate the boundary between realms.',
      lore: 'Veil Weavers see the threads connecting all three planes. By pulling and weaving these threads, they can heal allies, curse enemies, or tear holes in reality itself.',
      role: 'Healer/Support',
      startingAttributes: { Strength: 3, Vitality: 5, Endurance: 4, Dexterity: 3, Agility: 4, Intellect: 8, Wisdom: 8, Tactics: 5 },
      abilities: [
        { id: 'thread-mend', name: 'Thread Mend', icon: `${OS}icons/skills/cleric_1.png`, description: 'Weave reality to heal an ally for 2.0x magic power.', type: 'heal', damage: 2.0, manaCost: 20, staminaCost: 0, cooldown: 1, target: 'ally', effect: null },
        { id: 'veil-tear', name: 'Veil Tear', icon: `${OS}icons/skills/cleric_11.png`, description: 'Tear a hole in reality, dealing 1.6x arcane damage and lowering defense.', type: 'magical', damage: 1.6, manaCost: 25, staminaCost: 0, cooldown: 2, target: 'enemy', effect: 'lower_defense' },
        { id: 'planar-ward', name: 'Planar Ward', icon: `${OS}icons/skills/cleric_12.png`, description: 'Shield all allies with a veil barrier absorbing damage for 2 turns.', type: 'buff', damage: 0, manaCost: 30, staminaCost: 0, cooldown: 4, target: 'all_allies', effect: null },
        { id: 'soul-siphon', name: 'Soul Siphon', icon: `${OS}icons/skills/cleric_13.png`, description: 'Drain life from enemy, dealing 1.2x damage and healing self for same amount.', type: 'magical', damage: 1.2, manaCost: 20, staminaCost: 0, cooldown: 3, target: 'enemy', effect: null },
      ],
      signatureAbility: { id: 'reality-collapse', name: 'Reality Collapse', icon: `${OS}icons/skill_nobg/Archerskill_06_nobg.png`, description: 'Collapse all three planes together, dealing massive 2.5x arcane damage to all enemies and healing all allies.', type: 'magical', damage: 2.5, manaCost: 50, staminaCost: 0, cooldown: 10, target: 'all_enemies', effect: 'confuse' },
      transformAbility: { name: 'Planar Oracle', description: 'Merge with the Veil. Spells cost no mana, heals doubled, +30% all allies\' defense, 3 turns.' },
    },
    {
      id: 'doomcaller',
      name: 'Doom Caller',
      icon: `${OS}icons/skill_nobg/Archerskill_07_nobg.png`,
      color: '#eab308',
      description: 'Dark sorcerers who command curses and destructive magic.',
      lore: 'Doom Callers drew power directly from the Duskfall\'s epicenter. Their bodies carry the mark of the cataclysm, and their spells echo with the screams of those consumed by shadow.',
      role: 'Ranged DPS/Debuffer',
      startingAttributes: { Strength: 3, Vitality: 4, Endurance: 3, Dexterity: 5, Agility: 4, Intellect: 9, Wisdom: 6, Tactics: 6 },
      abilities: [
        { id: 'shadow-bolt', name: 'Shadow Bolt', icon: `${OS}icons/skills/darkmage_1.png`, description: 'Hurl a bolt of condensed shadow for 1.6x magic damage.', type: 'magical', damage: 1.6, manaCost: 15, staminaCost: 0, cooldown: 1, target: 'enemy', effect: null },
        { id: 'curse-of-decay', name: 'Curse of Decay', icon: `${OS}icons/skills/darkmage_11.png`, description: 'Curse target to take 0.5x damage per turn for 4 turns and lower attack by 20%.', type: 'debuff', damage: 0.5, manaCost: 25, staminaCost: 0, cooldown: 3, target: 'enemy', effect: 'poison' },
        { id: 'doom-nova', name: 'Doom Nova', icon: `${OS}icons/skills/darkmage_12.png`, description: 'Unleash shadow energy in all directions, hitting all enemies for 1.3x.', type: 'magical', damage: 1.3, manaCost: 30, staminaCost: 0, cooldown: 3, target: 'all_enemies', effect: null },
        { id: 'dark-pact', name: 'Dark Pact', icon: `${OS}icons/skills/darkmage_13.png`, description: 'Sacrifice 15% HP to gain +40% magic damage for 3 turns.', type: 'buff', damage: 0, manaCost: 0, staminaCost: 0, cooldown: 5, target: 'self', effect: null },
      ],
      signatureAbility: { id: 'cataclysm', name: 'Cataclysm', icon: `${OS}icons/skill_nobg/Archerskill_08_nobg.png`, description: 'Recreate the Duskfall in miniature. 4.0x shadow damage to all enemies, stuns for 1 turn.', type: 'magical', damage: 4.0, manaCost: 60, staminaCost: 0, cooldown: 12, target: 'all_enemies', effect: 'stun' },
      transformAbility: { name: 'Dusk Incarnate', description: 'Become the avatar of the Duskfall. All spells become AoE, +80% magic damage, enemies take shadow DOT, 3 turns.' },
    },
  ],

  attributes: [
    { name: 'Might', abbr: 'MGT', base: 'Strength', description: 'Raw physical power and melee damage', color: '#ef4444' },
    { name: 'Fortitude', abbr: 'FRT', base: 'Vitality', description: 'Life force and survivability', color: '#22c55e' },
    { name: 'Resolve', abbr: 'RSV', base: 'Endurance', description: 'Mental and physical stamina', color: '#f97316' },
    { name: 'Precision', abbr: 'PRC', base: 'Dexterity', description: 'Weapon mastery and critical strikes', color: '#eab308' },
    { name: 'Swiftness', abbr: 'SWF', base: 'Agility', description: 'Speed and evasion in combat', color: '#06b6d4' },
    { name: 'Arcana', abbr: 'ARC', base: 'Intellect', description: 'Mastery of shadow and ember magic', color: '#8b5cf6' },
    { name: 'Insight', abbr: 'INS', base: 'Wisdom', description: 'Planar awareness and healing power', color: '#3b82f6' },
    { name: 'Command', abbr: 'CMD', base: 'Tactics', description: 'Battlefield leadership and coordination', color: '#64748b' },
  ],

  enemies: [
    { id: 'shadow-wisp', name: 'Shadow Wisp', icon: `${OS}icons/496_rpg_icons/A_Armor04.png`, color: '#8b5cf6', portrait: '', baseHealth: 45, baseDamage: 12, baseDefense: 3, baseMana: 20, xpReward: 15, goldReward: 8, speed: 14, isBoss: false, abilities: ['shadow-bolt'], lore: 'Fragments of lost souls trapped in the Umbral Veil.' },
    { id: 'ember-imp', name: 'Ember Imp', icon: `${OS}icons/496_rpg_icons/A_Armor05.png`, color: '#ef4444', portrait: '', baseHealth: 55, baseDamage: 18, baseDefense: 4, baseMana: 15, xpReward: 18, goldReward: 10, speed: 12, isBoss: false, abilities: ['flame-spit'], lore: 'Mischievous fire sprites born from Ember Core vents.' },
    { id: 'veil-stalker', name: 'Veil Stalker', icon: `${OS}icons/496_rpg_icons/A_Armour01.png`, color: '#22d3ee', portrait: '', baseHealth: 70, baseDamage: 22, baseDefense: 6, baseMana: 10, xpReward: 25, goldReward: 15, speed: 16, isBoss: false, abilities: ['phase-strike', 'ambush'], lore: 'Predators that hunt in the space between planes.' },
    { id: 'crystal-golem', name: 'Crystal Golem', icon: `${OS}icons/496_rpg_icons/A_Armour02.png`, color: '#06b6d4', portrait: '', baseHealth: 150, baseDamage: 25, baseDefense: 18, baseMana: 0, xpReward: 35, goldReward: 25, speed: 5, isBoss: false, abilities: ['crystal-smash'], lore: 'Animated mineral constructs guarding Ember Core deposits.' },
    { id: 'dusk-hound', name: 'Dusk Hound', icon: `${OS}icons/496_rpg_icons/A_Armour03.png`, color: '#a855f7', portrait: '', baseHealth: 60, baseDamage: 20, baseDefense: 5, baseMana: 0, xpReward: 20, goldReward: 12, speed: 18, isBoss: false, abilities: ['savage-bite', 'howl'], lore: 'Shadow-touched wolves that hunt in packs.' },
    { id: 'plagued-knight', name: 'Plagued Knight', icon: `${OS}icons/496_rpg_icons/A_Armour04.png`, color: '#65a30d', portrait: '', baseHealth: 120, baseDamage: 28, baseDefense: 15, baseMana: 10, xpReward: 40, goldReward: 30, speed: 8, isBoss: false, abilities: ['plague-strike', 'shield-bash'], lore: 'Fallen knights reanimated by shadow corruption.' },
    { id: 'ash-wraith', name: 'Ash Wraith', icon: `${OS}icons/496_rpg_icons/A_Armour05.png`, color: '#f97316', portrait: '', baseHealth: 80, baseDamage: 30, baseDefense: 2, baseMana: 40, xpReward: 30, goldReward: 20, speed: 13, isBoss: false, abilities: ['fire-breath', 'ash-cloud'], lore: 'Spirits of those consumed by the Ember Core eruption.' },
    { id: 'void-spider', name: 'Void Spider', icon: `${OS}icons/496_rpg_icons/A_Armour06.png`, color: '#1e1b4b', portrait: '', baseHealth: 50, baseDamage: 15, baseDefense: 4, baseMana: 25, xpReward: 22, goldReward: 14, speed: 15, isBoss: false, abilities: ['web-trap', 'venom-bite'], lore: 'Arachnids that spin webs of shadow between dimensions.' },
    { id: 'corrupted-treant', name: 'Corrupted Treant', icon: `${OS}icons/496_rpg_icons/A_Armour07.png`, color: '#166534', portrait: '', baseHealth: 200, baseDamage: 20, baseDefense: 20, baseMana: 15, xpReward: 45, goldReward: 35, speed: 4, isBoss: false, abilities: ['root-slam', 'bark-shield'], lore: 'Ancient forest guardians warped by the Duskfall\'s corruption.' },
    { id: 'veil-assassin', name: 'Veil Assassin', icon: `${OS}icons/496_rpg_icons/A_Armour08.png`, color: '#6d28d9', portrait: '', baseHealth: 65, baseDamage: 35, baseDefense: 3, baseMana: 20, xpReward: 35, goldReward: 25, speed: 20, isBoss: false, abilities: ['backstab', 'vanish', 'poison-blade'], lore: 'Elite Dusk Elf rogues who serve the shadow lords.' },
    { id: 'flame-revenant', name: 'Flame Revenant', icon: `${OS}icons/496_rpg_icons/A_Armour09.png`, color: '#dc2626', portrait: '', baseHealth: 110, baseDamage: 32, baseDefense: 10, baseMana: 30, xpReward: 40, goldReward: 28, speed: 10, isBoss: false, abilities: ['fire-storm', 'flame-shield'], lore: 'Undead warriors permanently wreathed in ember fire.' },
    { id: 'shadow-drake', name: 'Shadow Drake', icon: `${OS}icons/496_rpg_icons/A_Armour10.png`, color: '#4c1d95', portrait: '', baseHealth: 180, baseDamage: 38, baseDefense: 14, baseMana: 35, xpReward: 60, goldReward: 45, speed: 12, isBoss: false, abilities: ['shadow-breath', 'tail-sweep', 'fear'], lore: 'Lesser dragons corrupted by the Umbral Veil.' },
    { id: 'obsidian-sentinel', name: 'Obsidian Sentinel', icon: `${OS}icons/496_rpg_icons/A_Armour11.png`, color: '#1c1917', portrait: '', baseHealth: 250, baseDamage: 30, baseDefense: 25, baseMana: 0, xpReward: 55, goldReward: 40, speed: 3, isBoss: false, abilities: ['obsidian-slam', 'fortify'], lore: 'Living statues of volcanic glass guarding ancient vaults.' },
    { id: 'mind-flayer', name: 'Mind Flayer', icon: `${OS}icons/496_rpg_icons/A_Armour12.png`, color: '#7c3aed', portrait: '', baseHealth: 90, baseDamage: 25, baseDefense: 8, baseMana: 60, xpReward: 50, goldReward: 35, speed: 11, isBoss: false, abilities: ['psychic-blast', 'confuse', 'mind-control'], lore: 'Aberrant creatures from deep within the Umbral Veil.' },
    { id: 'bone-legion', name: 'Bone Legionnaire', icon: `${OS}icons/496_rpg_icons/A_Armour13.png`, color: '#d6d3d1', portrait: '', baseHealth: 75, baseDamage: 22, baseDefense: 12, baseMana: 0, xpReward: 25, goldReward: 18, speed: 9, isBoss: false, abilities: ['bone-thrust', 'shield-wall'], lore: 'Animated skeletons of ancient soldiers marching endlessly.' },
    { id: 'ember-elemental', name: 'Ember Elemental', icon: `${OS}icons/496_rpg_icons/A_Armour14.png`, color: '#fb923c', portrait: '', baseHealth: 130, baseDamage: 35, baseDefense: 8, baseMana: 45, xpReward: 45, goldReward: 32, speed: 11, isBoss: false, abilities: ['eruption', 'magma-pool'], lore: 'Pure elemental energy given form by the Ember Core.' },
    { id: 'nightcrawler', name: 'Nightcrawler', icon: `${OS}icons/496_rpg_icons/A_Armour15.png`, color: '#1e1b4b', portrait: '', baseHealth: 95, baseDamage: 28, baseDefense: 6, baseMana: 30, xpReward: 38, goldReward: 25, speed: 17, isBoss: false, abilities: ['shadow-lunge', 'dark-shriek'], lore: 'Predatory creatures born from the deepest shadows.' },
    { id: 'doom-priest', name: 'Doom Priest', icon: `${OS}icons/496_rpg_icons/A_Armour16.png`, color: '#581c87', portrait: '', baseHealth: 85, baseDamage: 20, baseDefense: 7, baseMana: 50, xpReward: 42, goldReward: 30, speed: 9, isBoss: false, abilities: ['dark-heal', 'shadow-curse', 'summon-wisp'], lore: 'Corrupted clerics who worship the Duskfall as a god.' },
    { id: 'storm-gargoyle', name: 'Storm Gargoyle', icon: `${OS}icons/496_rpg_icons/A_Armour17.png`, color: '#64748b', portrait: '', baseHealth: 140, baseDamage: 30, baseDefense: 16, baseMana: 20, xpReward: 48, goldReward: 35, speed: 14, isBoss: false, abilities: ['dive-bomb', 'stone-gaze', 'lightning-strike'], lore: 'Animated stone guardians that patrol castle ruins.' },
    { id: 'blood-knight', name: 'Blood Knight', icon: `${OS}icons/496_rpg_icons/A_Armour18.png`, color: '#b91c1c', portrait: '', baseHealth: 160, baseDamage: 36, baseDefense: 14, baseMana: 15, xpReward: 55, goldReward: 42, speed: 10, isBoss: false, abilities: ['blood-strike', 'life-drain', 'frenzy'], lore: 'Vampiric warriors who heal by spilling enemy blood.' },
    { id: 'rift-horror', name: 'Rift Horror', icon: `${OS}icons/496_rpg_icons/A_Armour19.png`, color: '#4338ca', portrait: '', baseHealth: 200, baseDamage: 40, baseDefense: 12, baseMana: 40, xpReward: 65, goldReward: 50, speed: 8, isBoss: false, abilities: ['rift-slam', 'dimensional-tear', 'fear-aura'], lore: 'Monstrosities that crawled through planar rifts.' },
    { id: 'iron-juggernaut', name: 'Iron Juggernaut', icon: `${OS}icons/496_rpg_icons/A_Armour20.png`, color: '#78716c', portrait: '', baseHealth: 300, baseDamage: 35, baseDefense: 30, baseMana: 0, xpReward: 70, goldReward: 55, speed: 3, isBoss: false, abilities: ['steamroller', 'armor-up', 'ground-pound'], lore: 'War machines animated by shadow energy and ember fuel.' },
    { id: 'veil-serpent', name: 'Veil Serpent', icon: `${OS}icons/496_rpg_icons/A_Armour21.png`, color: '#059669', portrait: '', baseHealth: 120, baseDamage: 30, baseDefense: 8, baseMana: 35, xpReward: 45, goldReward: 33, speed: 16, isBoss: false, abilities: ['constrict', 'venom-spray', 'phase-coil'], lore: 'Enormous serpents that swim through the Umbral Veil.' },
    { id: 'doom-herald', name: 'Doom Herald', icon: `${OS}icons/496_rpg_icons/A_Armour22.png`, color: '#7c2d12', portrait: '', baseHealth: 180, baseDamage: 42, baseDefense: 15, baseMana: 50, xpReward: 75, goldReward: 60, speed: 10, isBoss: false, abilities: ['doom-decree', 'shadow-nova', 'summon-minions'], lore: 'Commanders of the shadow armies, speaking prophecies of destruction.' },
  ],

  bosses: [
    { id: 'lord-umbral', name: 'Lord Umbral, the Duskfather', icon: `${OS}icons/rpg_splash/rpg_splash_3.png`, color: '#6d28d9', portrait: `${OS}icons/rpg_splash/rpg_splash_3.png`, baseHealth: 2000, baseDamage: 55, baseDefense: 25, baseMana: 100, xpReward: 500, goldReward: 300, speed: 12, isBoss: true, abilities: ['shadow-storm', 'veil-rend', 'doom-pulse', 'summon-shades'], lore: 'The first Shadow Knight to be fully consumed by the Umbral Veil. Lord Umbral has become the living embodiment of the Duskfall, commanding an army of shadow creatures from his throne of darkness.', phases: [{ name: 'Shadow Lord', threshold: 100 }, { name: 'Veil Incarnate', threshold: 50 }, { name: 'Duskfall Avatar', threshold: 25 }] },
    { id: 'queen-cinder', name: 'Queen Cinder, the Ember Tyrant', icon: `${OS}icons/rpg_splash/rpg_splash_8.png`, color: '#dc2626', portrait: `${OS}icons/rpg_splash/rpg_splash_8.png`, baseHealth: 2200, baseDamage: 60, baseDefense: 20, baseMana: 80, xpReward: 550, goldReward: 350, speed: 10, isBoss: true, abilities: ['inferno-rain', 'magma-eruption', 'phoenix-rebirth', 'flame-prison'], lore: 'Once a noble queen, she sacrificed her humanity to control the Ember Core. Now she rules the volcanic wastes, her body an ever-burning vessel of destruction.', phases: [{ name: 'Ember Queen', threshold: 100 }, { name: 'Magma Form', threshold: 50 }, { name: 'Supernova', threshold: 20 }] },
    { id: 'the-hollow-king', name: 'The Hollow King', icon: `${OS}icons/rpg_splash/rpg_splash_15.png`, color: '#22d3ee', portrait: `${OS}icons/rpg_splash/rpg_splash_15.png`, baseHealth: 2500, baseDamage: 50, baseDefense: 30, baseMana: 120, xpReward: 600, goldReward: 400, speed: 8, isBoss: true, abilities: ['soul-harvest', 'reality-shatter', 'undead-legion', 'crown-of-thorns'], lore: 'The last king of Valtheris, who tried to undo the Duskfall but instead became trapped between all three planes. His hollow crown still radiates the power that once held the kingdom together.', phases: [{ name: 'Hollow Monarch', threshold: 100 }, { name: 'Between Worlds', threshold: 40 }, { name: 'Planar Collapse', threshold: 15 }] },
    { id: 'the-duskfall', name: 'The Duskfall Itself', icon: `${OS}icons/rpg_splash/rpg_splash_20.png`, color: '#1e1b4b', portrait: `${OS}icons/rpg_splash/rpg_splash_20.png`, baseHealth: 3500, baseDamage: 70, baseDefense: 35, baseMana: 200, xpReward: 1000, goldReward: 600, speed: 15, isBoss: true, abilities: ['reality-collapse', 'oblivion-pulse', 'plane-merge', 'shadow-rebirth', 'final-cataclysm'], lore: 'The Duskfall was never a natural disaster — it was a living entity. A sentient collapse of reality itself, consuming all light and order. To defeat it is to rewrite the laws of existence.', phases: [{ name: 'Awakening', threshold: 100 }, { name: 'Convergence', threshold: 60 }, { name: 'Singularity', threshold: 30 }, { name: 'Annihilation', threshold: 10 }] },
  ],

  equipment: {
    slots: ['weapon', 'offhand', 'helmet', 'armor', 'feet', 'ring', 'relic'],
    tiers: ['Iron', 'Shadow Steel', 'Ember Forged', 'Veil Touched', 'Soul Bound', 'Dusk Tempered', 'Planar', 'Cataclysmic'],
    weaponTypes: [
      { id: 'shadow-blade', name: 'Shadow Blade', base: 'sword', icon: `${OS}icons/weapons/greatsword.png`, slot: 'weapon', statBonus: 'Might' },
      { id: 'veil-fang', name: 'Veil Fang', base: 'dagger', icon: `${OS}icons/weapons/dagger.png`, slot: 'weapon', statBonus: 'Precision' },
      { id: 'ember-staff', name: 'Ember Staff', base: 'staff', icon: `${OS}icons/weapons/staff.png`, slot: 'weapon', statBonus: 'Arcana' },
      { id: 'veil-grimoire', name: 'Veil Grimoire', base: 'tome', icon: `${OS}icons/weapons/arcane-tome.png`, slot: 'weapon', statBonus: 'Insight' },
      { id: 'iron-bulwark', name: 'Iron Bulwark', base: 'shield', icon: `${OS}icons/weapons/shield.png`, slot: 'offhand', statBonus: 'Fortitude' },
      { id: 'dusk-cleaver', name: 'Dusk Cleaver', base: 'axe', icon: `${OS}icons/weapons/greatsword.png`, slot: 'weapon', statBonus: 'Might' },
      { id: 'doom-spear', name: 'Doom Spear', base: 'lance', icon: `${OS}icons/weapons/greatsword.png`, slot: 'weapon', statBonus: 'Might' },
      { id: 'shadow-bow', name: 'Shadow Bow', base: 'bow', icon: `${OS}icons/weapons/dagger.png`, slot: 'weapon', statBonus: 'Precision' },
      { id: 'ember-maul', name: 'Ember Maul', base: 'hammer', icon: `${OS}icons/weapons/greatsword.png`, slot: 'weapon', statBonus: 'Resolve' },
    ],
    armorSets: [
      { id: 'shadow-set', name: 'Shadow Weave Set', color: '#8b5cf6', bonusDescription: '2pc: +10% shadow damage, 4pc: +20% crit chance' },
      { id: 'ember-set', name: 'Ember Plate Set', color: '#ef4444', bonusDescription: '2pc: +15% fire resistance, 4pc: +25% max HP' },
      { id: 'veil-set', name: 'Veil Silk Set', color: '#06b6d4', bonusDescription: '2pc: +15% mana regen, 4pc: +30% healing power' },
      { id: 'doom-set', name: 'Doom Lord Set', color: '#eab308', bonusDescription: '2pc: +10% all damage, 4pc: +20% spell damage, DOTs deal +25%' },
    ],
    items: [],
  },

  lore: {
    title: 'The Chronicle of Duskfall',
    subtitle: 'A Tale of Three Planes',
    prologue: 'Before the Duskfall, Valtheris was a beacon of civilization. Three ancient pillars — the Mortal Anchor, the Umbral Gate, and the Ember Seal — kept the three planes of existence separated. When the mad archmage Kethros attempted to merge all three planes to achieve godhood, the pillars shattered. The resulting cataclysm — the Duskfall — tore reality apart. Now shadow bleeds into light, fire erupts from stone, and the dead walk among the living. Only the Shadow Knights, warriors who learned to channel the chaos, stand between Valtheris and total oblivion.',
    factions: [
      { name: 'The Iron Covenant', description: 'Remnant knights sworn to restore the three pillars.', color: '#94a3b8' },
      { name: 'The Umbral Court', description: 'Shadow-worshippers who believe the Duskfall is evolution.', color: '#8b5cf6' },
      { name: 'The Ember Forge', description: 'Dwarf-led faction harnessing the Ember Core\'s power for good.', color: '#f97316' },
    ],
    worldHistory: 'Three thousand years of peace shattered in a single night. The Duskfall claimed half the kingdom\'s population in minutes. Those who survived found themselves changed — some gaining powers, others becoming monsters. Now, two years later, the Shadow Knights emerge as the last hope.',
  },

  chapters: [
    { id: 'ch1', number: 1, title: 'Echoes of the Fall', subtitle: 'Awaken in the aftermath', description: 'You awaken in the ruins of Fort Ironhold, the last bastion of the Iron Covenant. Shadow creatures prowl the perimeter. Master the basics of combat and find your first allies.', color: '#94a3b8', objectives: ['Create 2 heroes', 'Win 3 battles', 'Reach the Ashen Village'], rewards: { xp: 200, currency: 100 }, loreReveal: 'The Duskfall was caused by Archmage Kethros\' failed ritual to merge the three planes.' },
    { id: 'ch2', number: 2, title: 'Flames Beneath', subtitle: 'Discover the Ember Core', description: 'The Ember Dwarves have detected a growing instability in the Ember Core. Journey to the Molten Depths and prevent a second cataclysm.', color: '#f97316', objectives: ['Explore Molten Depths', 'Defeat 10 Ember enemies', 'Find the Ember Shard'], rewards: { xp: 400, currency: 200 }, loreReveal: 'The Ember Core is the heart of creation itself — destroying it would unmake all matter.' },
    { id: 'ch3', number: 3, title: 'Veil of Shadows', subtitle: 'Enter the Umbral Veil', description: 'The Umbral Court is growing stronger. Cross into the Shadow Plane to disrupt their rituals before they can summon Lord Umbral to full power.', color: '#8b5cf6', objectives: ['Enter the Umbral Veil', 'Defeat Lord Umbral', 'Seal the Shadow Gate'], rewards: { xp: 600, currency: 300 }, loreReveal: 'Lord Umbral was once the king\'s champion, twisted by his desire to protect Valtheris at any cost.' },
    { id: 'ch4', number: 4, title: 'The Burning Throne', subtitle: 'Face the Ember Tyrant', description: 'Queen Cinder has seized control of the Ember Forge. Without it, the dwarves cannot repair the pillars. Storm the Volcanic Citadel and dethrone her.', color: '#dc2626', objectives: ['Storm Volcanic Citadel', 'Defeat Queen Cinder', 'Reclaim the Ember Forge'], rewards: { xp: 800, currency: 400 }, loreReveal: 'Queen Cinder sacrificed her kingdom to save her daughter, who became the first Crystalborn.' },
    { id: 'ch5', number: 5, title: 'The Hollow Crown', subtitle: 'Confront the dead king', description: 'The Hollow King stirs in his tomb between worlds. His crown holds the key to restoring the Mortal Anchor. But he will not relinquish it willingly.', color: '#22d3ee', objectives: ['Find the Tomb Between Worlds', 'Defeat the Hollow King', 'Claim the Hollow Crown'], rewards: { xp: 1000, currency: 500 }, loreReveal: 'The Hollow King tried to reverse the Duskfall and was torn apart across all three planes.' },
    { id: 'ch6', number: 6, title: 'Duskfall\'s End', subtitle: 'Unmake the cataclysm', description: 'Armed with the Hollow Crown, the Ember Shard, and the Shadow Seal, you stand before the Duskfall itself. This living cataclysm must be unmade — or all of reality will collapse into one endless shadow.', color: '#1e1b4b', objectives: ['Forge the Pillar Key', 'Enter the Duskfall', 'Defeat the Duskfall Entity', 'Restore the three planes'], rewards: { xp: 2000, currency: 1000 }, loreReveal: 'The Duskfall is not destruction — it is a new form of existence. Defeating it means choosing the old world over the new.' },
  ],

  worldMap: {
    name: 'Valtheris',
    regions: [
      { id: 'ashen-lowlands', name: 'Ashen Lowlands', color: '#94a3b8', description: 'The scorched farmlands surrounding old Valtheris, now haunted by shadow wisps.', terrainType: 'plains', levelRange: [1, 5] },
      { id: 'umbral-forest', name: 'Umbral Forest', color: '#8b5cf6', description: 'Ancient woods where shadow and light flicker between planes.', terrainType: 'forest', levelRange: [4, 10] },
      { id: 'molten-depths', name: 'Molten Depths', color: '#f97316', description: 'Underground tunnels leading to the Ember Core, filled with fire elementals.', terrainType: 'volcanic', levelRange: [8, 14] },
      { id: 'veil-wastes', name: 'Veil Wastes', color: '#22d3ee', description: 'A desolate expanse where reality is thinnest and the planes overlap.', terrainType: 'wasteland', levelRange: [12, 18] },
      { id: 'duskfall-nexus', name: 'Duskfall Nexus', color: '#1e1b4b', description: 'The epicenter of the cataclysm, where all three planes collide.', terrainType: 'void', levelRange: [16, 20] },
    ],
    locations: [
      { id: 'fort-ironhold', name: 'Fort Ironhold', region: 'ashen-lowlands', x: 15, y: 70, description: 'Last bastion of the Iron Covenant.', lore: 'Where the Shadow Knights first organized.', enemyPool: ['shadow-wisp', 'ember-imp'], levelRange: [1, 3], type: 'camp', background: `${OS}icons/rpg_splash/rpg_splash_2.png`, unlockRequirement: null },
      { id: 'ashen-village', name: 'Ashen Village', region: 'ashen-lowlands', x: 25, y: 60, description: 'A survivor settlement in the scorched lowlands.', lore: 'Built from the ruins of three towns.', enemyPool: ['shadow-wisp', 'dusk-hound'], levelRange: [2, 4], type: 'city', background: `${OS}icons/rpg_splash/rpg_splash_4.png`, unlockRequirement: null },
      { id: 'shadow-road', name: 'Shadow Road', region: 'ashen-lowlands', x: 35, y: 55, description: 'The main highway, now crawling with shadow creatures.', lore: 'Once connected all of Valtheris.', enemyPool: ['shadow-wisp', 'dusk-hound', 'veil-stalker'], levelRange: [3, 5], type: 'field', background: `${OS}icons/rpg_splash/rpg_splash_6.png`, unlockRequirement: null },
      { id: 'duskwatch-tower', name: 'Duskwatch Tower', region: 'ashen-lowlands', x: 40, y: 45, description: 'Ruined watchtower with a view of the Umbral Forest.', lore: 'The last signal fire before the fall.', enemyPool: ['veil-stalker', 'plagued-knight'], levelRange: [4, 6], type: 'dungeon', background: `${OS}icons/rpg_splash/rpg_splash_7.png`, unlockRequirement: 'ch1' },
      { id: 'whispering-glade', name: 'Whispering Glade', region: 'umbral-forest', x: 50, y: 40, description: 'A clearing where shadow voices echo endlessly.', lore: 'Trees here grow in both planes simultaneously.', enemyPool: ['veil-stalker', 'void-spider', 'corrupted-treant'], levelRange: [5, 8], type: 'field', background: `${OS}icons/rpg_splash/rpg_splash_9.png`, unlockRequirement: null },
      { id: 'shadow-grove', name: 'Shadow Grove', region: 'umbral-forest', x: 55, y: 35, description: 'Deep forest where the Umbral Veil is visible.', lore: 'Dusk Elves make their home here.', enemyPool: ['veil-assassin', 'nightcrawler', 'void-spider'], levelRange: [6, 9], type: 'field', background: `${OS}icons/rpg_splash/rpg_splash_10.png`, unlockRequirement: null },
      { id: 'moonfall-ruins', name: 'Moonfall Ruins', region: 'umbral-forest', x: 60, y: 30, description: 'Ruins of a temple to the old moon goddess.', lore: 'Where the Umbral Gate pillar once stood.', enemyPool: ['mind-flayer', 'doom-priest', 'shadow-drake'], levelRange: [7, 10], type: 'dungeon', background: `${OS}icons/rpg_splash/rpg_splash_11.png`, unlockRequirement: 'ch2' },
      { id: 'umbral-gate', name: 'Umbral Gate', region: 'umbral-forest', x: 65, y: 25, description: 'The shattered entrance to the Shadow Plane.', lore: 'Lord Umbral crossed through here.', enemyPool: ['veil-assassin', 'shadow-drake', 'mind-flayer'], levelRange: [9, 12], type: 'boss', background: `${OS}icons/rpg_splash/rpg_splash_13.png`, unlockRequirement: 'ch3' },
      { id: 'ember-descent', name: 'Ember Descent', region: 'molten-depths', x: 55, y: 55, description: 'The fiery staircase leading underground.', lore: 'Ember Dwarves carved this path millennia ago.', enemyPool: ['ember-imp', 'ash-wraith', 'crystal-golem'], levelRange: [8, 11], type: 'dungeon', background: `${OS}icons/rpg_splash/rpg_splash_14.png`, unlockRequirement: null },
      { id: 'forge-halls', name: 'Forge Halls', region: 'molten-depths', x: 60, y: 60, description: 'Ancient dwarven forges still blazing with ember fire.', lore: 'Where Soul Iron was first smelted.', enemyPool: ['crystal-golem', 'flame-revenant', 'ember-elemental'], levelRange: [10, 13], type: 'trading', background: `${OS}icons/rpg_splash/rpg_splash_16.png`, unlockRequirement: null },
      { id: 'magma-lake', name: 'Magma Lake', region: 'molten-depths', x: 65, y: 65, description: 'A vast lake of molten rock surrounding the Ember Core.', lore: 'The heat here is beyond mortal endurance without protection.', enemyPool: ['ember-elemental', 'flame-revenant', 'iron-juggernaut'], levelRange: [11, 14], type: 'field', background: `${OS}icons/rpg_splash/rpg_splash_17.png`, unlockRequirement: 'ch3' },
      { id: 'volcanic-citadel', name: 'Volcanic Citadel', region: 'molten-depths', x: 70, y: 70, description: 'Queen Cinder\'s fortress built within the volcano.', lore: 'Once the Ember Forge, now a tyrant\'s throne.', enemyPool: ['flame-revenant', 'iron-juggernaut', 'ember-elemental'], levelRange: [13, 16], type: 'boss', background: `${OS}icons/rpg_splash/rpg_splash_19.png`, unlockRequirement: 'ch4' },
      { id: 'rift-crossing', name: 'Rift Crossing', region: 'veil-wastes', x: 70, y: 35, description: 'Where dimensional rifts open and close unpredictably.', lore: 'Travelers here sometimes step into other timelines.', enemyPool: ['rift-horror', 'veil-serpent', 'nightcrawler'], levelRange: [13, 16], type: 'field', background: `${OS}icons/rpg_splash/rpg_splash_21.png`, unlockRequirement: null },
      { id: 'bone-fields', name: 'Bone Fields', region: 'veil-wastes', x: 75, y: 30, description: 'Endless plains of skeletal remains from the Duskfall.', lore: 'The dead here sometimes rise and march.', enemyPool: ['bone-legion', 'plagued-knight', 'doom-herald'], levelRange: [14, 17], type: 'field', background: `${OS}icons/rpg_splash/rpg_splash_22.png`, unlockRequirement: null },
      { id: 'tomb-between', name: 'Tomb Between Worlds', region: 'veil-wastes', x: 80, y: 25, description: 'The resting place of the Hollow King, existing in all three planes.', lore: 'Time moves differently here.', enemyPool: ['doom-herald', 'blood-knight', 'storm-gargoyle'], levelRange: [16, 18], type: 'boss', background: `${OS}icons/rpg_splash/rpg_splash_23.png`, unlockRequirement: 'ch5' },
      { id: 'pillar-ruins', name: 'Pillar Ruins', region: 'veil-wastes', x: 85, y: 20, description: 'Where the Mortal Anchor pillar once stood.', lore: 'Fragments of the pillar still hum with power.', enemyPool: ['obsidian-sentinel', 'rift-horror', 'doom-herald'], levelRange: [15, 18], type: 'dungeon', background: `${OS}icons/rpg_splash/rpg_splash_24.png`, unlockRequirement: 'ch4' },
      { id: 'shadow-throne', name: 'Shadow Throne', region: 'duskfall-nexus', x: 85, y: 50, description: 'Lord Umbral\'s seat of power in the shadow plane.', lore: 'A mockery of the old royal palace.', enemyPool: ['doom-herald', 'blood-knight', 'shadow-drake'], levelRange: [17, 19], type: 'dungeon', background: `${OS}icons/rpg_splash/rpg_splash_26.png`, unlockRequirement: 'ch5' },
      { id: 'convergence-point', name: 'Convergence Point', region: 'duskfall-nexus', x: 88, y: 45, description: 'Where all three planes visibly overlap.', lore: 'Reality here is like wet paint — malleable.', enemyPool: ['rift-horror', 'iron-juggernaut', 'doom-herald'], levelRange: [18, 20], type: 'field', background: `${OS}icons/rpg_splash/rpg_splash_28.png`, unlockRequirement: 'ch5' },
      { id: 'kethros-sanctum', name: 'Kethros\' Sanctum', region: 'duskfall-nexus', x: 90, y: 40, description: 'The mad archmage\'s laboratory where it all began.', lore: 'His notes reveal the truth about the Duskfall.', enemyPool: ['mind-flayer', 'doom-herald', 'rift-horror'], levelRange: [19, 20], type: 'dungeon', background: `${OS}icons/rpg_splash/rpg_splash_29.png`, unlockRequirement: 'ch6' },
      { id: 'duskfall-heart', name: 'Heart of the Duskfall', region: 'duskfall-nexus', x: 92, y: 35, description: 'The living center of the cataclysm itself.', lore: 'This is where reality ends and begins anew.', enemyPool: [], levelRange: [20, 20], type: 'boss', background: `${OS}icons/rpg_splash/rpg_splash_31.png`, unlockRequirement: 'ch6' },
    ],
    connections: [
      ['fort-ironhold', 'ashen-village'], ['ashen-village', 'shadow-road'], ['shadow-road', 'duskwatch-tower'],
      ['duskwatch-tower', 'whispering-glade'], ['whispering-glade', 'shadow-grove'], ['shadow-grove', 'moonfall-ruins'],
      ['moonfall-ruins', 'umbral-gate'], ['shadow-road', 'ember-descent'], ['ember-descent', 'forge-halls'],
      ['forge-halls', 'magma-lake'], ['magma-lake', 'volcanic-citadel'], ['umbral-gate', 'rift-crossing'],
      ['rift-crossing', 'bone-fields'], ['bone-fields', 'tomb-between'], ['tomb-between', 'pillar-ruins'],
      ['pillar-ruins', 'shadow-throne'], ['shadow-throne', 'convergence-point'], ['convergence-point', 'kethros-sanctum'],
      ['kethros-sanctum', 'duskfall-heart'],
    ],
  },

  dialogue: {
    greetings: ['The shadows grow restless... as do I.', 'Another dawn survived. That\'s something.', 'Keep your blade close. The Veil is thin today.', 'I can feel the Ember Core pulsing beneath our feet.'],
    battleCries: ['For Valtheris!', 'By shadow and flame!', 'The Duskfall ends with us!', 'Into the Veil!', 'Let darkness fear the light we carry!'],
    victory: ['The shadows retreat... for now.', 'Another battle won. The tide is turning.', 'Their strength feeds our resolve.', 'The Duskfall\'s grip weakens.'],
    defeat: ['We cannot fall here... not when so much depends on us.', 'The shadows claim another...', 'Regroup. The Duskfall will not win today.', 'Even in defeat, we learn.'],
    idle: ['Can you hear it? The Veil whispers...', 'I wonder what Valtheris looked like before the Fall.', 'The ember in my veins grows stronger each day.', 'Shadow and flame — which will outlast the other?'],
  },

  assets: {
    backgrounds: [
      { id: 'title', path: `${OS}icons/rpg_splash/rpg_splash_1.png`, description: 'Title screen background' },
      { id: 'battle-plains', path: `${OS}icons/rpg_splash/rpg_splash_6.png`, description: 'Ashen Lowlands battle backdrop' },
      { id: 'battle-forest', path: `${OS}icons/rpg_splash/rpg_splash_10.png`, description: 'Umbral Forest battle backdrop' },
      { id: 'battle-volcano', path: `${OS}icons/rpg_splash/rpg_splash_17.png`, description: 'Molten Depths battle backdrop' },
      { id: 'battle-wastes', path: `${OS}icons/rpg_splash/rpg_splash_22.png`, description: 'Veil Wastes battle backdrop' },
      { id: 'battle-nexus', path: `${OS}icons/rpg_splash/rpg_splash_29.png`, description: 'Duskfall Nexus battle backdrop' },
    ],
    raceSprites: [
      { id: 'ironborn-sprite', race: 'ironborn', path: `${OS}icons/rpg_splash/rpg_splash_1.png` },
      { id: 'duskelf-sprite', race: 'duskelf', path: `${OS}icons/rpg_splash/rpg_splash_5.png` },
      { id: 'emberdwarf-sprite', race: 'emberdwarf', path: `${OS}icons/rpg_splash/rpg_splash_12.png` },
      { id: 'wraithkin-sprite', race: 'wraithkin', path: `${OS}icons/rpg_splash/rpg_splash_18.png` },
      { id: 'beastblood-sprite', race: 'beastblood', path: `${OS}icons/rpg_splash/rpg_splash_25.png` },
      { id: 'crystalborn-sprite', race: 'crystalborn', path: `${OS}icons/rpg_splash/rpg_splash_30.png` },
    ],
    enemySprites: [],
    icons: [
      { id: 'currency', path: `${OS}icons/materials/ancient-essence.png`, type: 'currency' },
      { id: 'shadow-essence', path: `${OS}icons/materials/adamantine-ore.png`, type: 'resource' },
      { id: 'ember-shard', path: `${OS}icons/materials/adamantine-ingot.png`, type: 'resource' },
    ],
    effects: [],
    uiElements: [],
  },

  battleSystem: {
    type: 'turn-based',
    positioning: '4-row (Front/Mid-Front/Mid-Back/Back)',
    initiative: 'speed-based',
    partySize: 4,
    effects: ['bleed', 'burn', 'poison', 'stun', 'sleep', 'confuse', 'lower_defense', 'lower_attack'],
    mechanics: ['guardian-intercept', 'transformation', 'skill-tree-passives', 'weapon-skills', 'planar-shift'],
  },
};
