const OS = 'https://molochdagod.github.io/ObjectStore/';

export const STARBOUND_CORSAIRS_SPEC = {
  meta: {
    id: 'starbound-corsairs',
    gameName: 'Starbound Corsairs',
    studioName: 'Grudge Studios',
    tagline: 'Plunder the Stars, Rule the Void',
    version: '1.0.0',
    theme: 'space-pirate-rpg',
    setting: 'The Shattered Expanse — a lawless sector of space where the galactic government collapsed after the Rift Wars. Pirates, bounty hunters, and rogue AI factions now battle over ancient alien tech, rare minerals, and control of the jump gates that connect distant star systems.',
    artStyle: 'pixel',
    colorPalette: {
      primary: '#22d3ee',
      secondary: '#f97316',
      accent: '#a855f7',
      danger: '#ef4444',
      background: '#020617',
      text: '#e2e8f0',
    },
    fonts: { heading: 'Cinzel', body: 'Jost' },
    currency: { name: 'Credits', icon: 'coin', plural: 'Credits' },
    resources: [
      { name: 'Plasma Cores', icon: 'gem', description: 'Unstable energy cells harvested from dying stars' },
      { name: 'Void Alloy', icon: 'ingot', description: 'Meta-material found only in rift anomalies' },
      { name: 'Bio-Gel', icon: 'herb', description: 'Organic compound from xenoflora colonies' },
      { name: 'Data Shards', icon: 'ore', description: 'Encrypted fragments of ancient alien knowledge' },
    ],
    objectStoreBase: OS,
    battleBackgrounds: [
      '/backgrounds/factory/starbound-corsairs/asteroid_belt.png',
      '/backgrounds/factory/starbound-corsairs/space_station.png',
      '/backgrounds/factory/starbound-corsairs/nebula_field.png',
      '/backgrounds/factory/starbound-corsairs/alien_planet.png',
      '/backgrounds/factory/starbound-corsairs/rift_anomaly.png',
    ],
  },

  raceCount: 6,
  classCount: 4,
  attributeCount: 8,
  enemyCount: 24,
  bossCount: 4,
  locationCount: 20,
  chapterCount: 6,
  skillTierCount: 4,
  equipmentTierCount: 8,

  races: [
    {
      id: 'terran',
      name: 'Terran',
      icon: `${OS}icons/rpg_splash/rpg_splash_32.png`,
      color: '#94a3b8',
      description: 'Resourceful humans who spread across the stars after Earth fell silent.',
      lore: 'When Earth went dark during the Rift Wars, scattered human colonies were forced to survive on their own. Terrans adapted to every environment, from frozen moons to volcanic worlds, becoming the most versatile species in the Expanse.',
      bonuses: { Strength: 1, Vitality: 1, Endurance: 1, Dexterity: 1, Agility: 1, Intellect: 1, Wisdom: 1, Tactics: 1 },
      passive: '+1 to all attributes',
      trait: 'Adaptable',
      traitDescription: 'Terrans gain a balanced bonus to all stats, effective in every role.',
    },
    {
      id: 'voidborn',
      name: 'Voidborn',
      icon: `${OS}icons/rpg_splash/rpg_splash_33.png`,
      color: '#a855f7',
      description: 'Mutated humans born in deep space, attuned to rift energy.',
      lore: 'Generations of exposure to rift radiation created the Voidborn — humans with elongated limbs, bioluminescent skin, and an innate ability to sense jump gate frequencies. They see the universe in spectrums invisible to others.',
      bonuses: { Intellect: 4, Wisdom: 2, Agility: 2 },
      passive: '+4 INT, +2 WIS, +2 AGI',
      trait: 'Rift Sense',
      traitDescription: 'Voidborn detect hidden enemies and have +15% accuracy against cloaked targets.',
    },
    {
      id: 'mekari',
      name: 'Mekari',
      icon: `${OS}icons/rpg_splash/rpg_splash_34.png`,
      color: '#f97316',
      description: 'Cyborg engineers who merged with their own war machines.',
      lore: 'The Mekari were once brilliant engineers who voluntarily fused their nervous systems with combat mech suits. Over decades, the boundary between pilot and machine vanished. They are walking weapons platforms with organic cores.',
      bonuses: { Strength: 3, Vitality: 3, Endurance: 2 },
      passive: '+3 STR, +3 VIT, +2 END',
      trait: 'Machine Hybrid',
      traitDescription: 'Mekari gain +10% armor and can self-repair 5% HP per turn below 40% health.',
    },
    {
      id: 'zephyri',
      name: 'Zephyri',
      icon: `${OS}icons/rpg_splash/rpg_splash_35.png`,
      color: '#22d3ee',
      description: 'Insectoid aliens with crystalline exoskeletons and hive intelligence.',
      lore: 'The Zephyri swarm arrived through a rift from another galaxy. Individual Zephyri are brilliant tacticians; in groups, their linked minds become supercomputers. Their crystal carapaces refract energy weapons.',
      bonuses: { Agility: 3, Dexterity: 3, Tactics: 2 },
      passive: '+3 AGI, +3 DEX, +2 TAC',
      trait: 'Hive Link',
      traitDescription: 'When multiple Zephyri are in the party, each gains +5% to all stats.',
    },
    {
      id: 'draconid',
      name: 'Draconid',
      icon: `${OS}icons/rpg_splash/rpg_splash_36.png`,
      color: '#ef4444',
      description: 'Reptilian warriors from a high-gravity homeworld, built for combat.',
      lore: 'Draconids evolved on a planet with 3x standard gravity, making them immensely strong in normal conditions. Their scaled hides resist energy weapons, and their dual hearts give them incredible endurance in prolonged battles.',
      bonuses: { Strength: 4, Endurance: 3, Vitality: 1 },
      passive: '+4 STR, +3 END, +1 VIT',
      trait: 'Dual Hearts',
      traitDescription: 'Draconids gain +20% stamina regeneration and resist stun effects.',
    },
    {
      id: 'phantari',
      name: 'Phantari',
      icon: `${OS}icons/rpg_splash/rpg_splash_37.png`,
      color: '#06b6d4',
      description: 'Shapeshifting energy beings who exist partially in the rift dimension.',
      lore: 'The Phantari are the oldest known species in the Expanse. They exist as stable energy patterns that can temporarily solidify into physical forms. When threatened, they phase-shift between dimensions.',
      bonuses: { Intellect: 3, Agility: 3, Wisdom: 2 },
      passive: '+3 INT, +3 AGI, +2 WIS',
      trait: 'Phase Shift',
      traitDescription: 'Phantari have a 15% chance to avoid damage by shifting into the rift dimension.',
    },
  ],

  classes: [
    {
      id: 'gunslinger',
      name: 'Gunslinger',
      icon: `${OS}icons/skill_nobg/Archerskill_09_nobg.png`,
      color: '#f97316',
      description: 'Dual-wielding sharpshooters who never miss their mark.',
      lore: 'Gunslingers are the fastest draws in the Expanse. Armed with plasma pistols and kinetic revolvers, they dispatch targets with surgical precision. Their reputation alone is enough to clear a cantina.',
      role: 'Ranged DPS',
      shipType: 'player/ship1',
      missileType: 'plasma',
      startingAttributes: { Strength: 4, Vitality: 4, Endurance: 3, Dexterity: 9, Agility: 7, Intellect: 4, Wisdom: 3, Tactics: 6 },
      abilities: [
        { id: 'quick-draw', name: 'Quick Draw', icon: `${OS}icons/skills/aeromancer_1.png`, description: 'Fire two rapid shots dealing 0.9x damage each.', type: 'physical', damage: 0.9, manaCost: 0, staminaCost: 15, cooldown: 1, target: 'enemy', effect: null },
        { id: 'plasma-shot', name: 'Plasma Shot', icon: `${OS}icons/skills/aeromancer_11.png`, description: 'Supercharged energy blast dealing 2.0x damage with burn chance.', type: 'physical', damage: 2.0, manaCost: 10, staminaCost: 20, cooldown: 3, target: 'enemy', effect: 'burn' },
        { id: 'fan-fire', name: 'Fan the Hammer', icon: `${OS}icons/skills/aeromancer_12.png`, description: 'Empty both clips hitting all enemies for 0.6x each.', type: 'physical', damage: 0.6, manaCost: 0, staminaCost: 30, cooldown: 4, target: 'all_enemies', effect: null },
        { id: 'dead-eye', name: 'Dead Eye', icon: `${OS}icons/skills/aeromancer_13.png`, description: 'Enter focus mode: next 3 attacks have +50% crit chance and +30% damage.', type: 'buff', damage: 0, manaCost: 5, staminaCost: 15, cooldown: 5, target: 'self', effect: null },
      ],
      signatureAbility: { id: 'meteor-barrage', name: 'Meteor Barrage', icon: `${OS}icons/skill_nobg/Archerskill_10_nobg.png`, description: 'Call in orbital fire support, raining plasma on all enemies for 2.5x damage.', type: 'physical', damage: 2.5, manaCost: 25, staminaCost: 30, cooldown: 8, target: 'all_enemies', effect: 'burn' },
      transformAbility: { name: 'Bullet Time', description: 'Enter hyper-focus. Attack 3 times per turn, +80% crit chance, +50% evasion, 3 turns.' },
    },
    {
      id: 'vanguard',
      name: 'Vanguard',
      icon: `${OS}icons/skill_nobg/Archerskill_11_nobg.png`,
      color: '#ef4444',
      description: 'Heavy armor specialists who lead every boarding action.',
      lore: 'Vanguards are the first through the airlock and the last to retreat. Encased in powered exo-armor, they absorb punishing damage while their heavy weapons turn corridors into kill zones.',
      role: 'Tank/Frontline',
      shipType: 'player/ship2',
      missileType: 'missile',
      startingAttributes: { Strength: 8, Vitality: 8, Endurance: 6, Dexterity: 3, Agility: 3, Intellect: 3, Wisdom: 4, Tactics: 5 },
      abilities: [
        { id: 'shield-slam', name: 'Shield Slam', icon: `${OS}icons/skills/berserker_1.png`, description: 'Bash with energy shield dealing 1.5x and stunning target.', type: 'physical', damage: 1.5, manaCost: 0, staminaCost: 20, cooldown: 2, target: 'enemy', effect: 'stun' },
        { id: 'energy-barrier', name: 'Energy Barrier', icon: `${OS}icons/skills/berserker_11.png`, description: 'Deploy a personal shield absorbing the next 300 damage.', type: 'buff', damage: 0, manaCost: 15, staminaCost: 15, cooldown: 3, target: 'self', effect: null },
        { id: 'heavy-ordnance', name: 'Heavy Ordnance', icon: `${OS}icons/skills/berserker_12.png`, description: 'Fire rocket launcher dealing 2.5x splash damage.', type: 'physical', damage: 2.5, manaCost: 0, staminaCost: 35, cooldown: 5, target: 'enemy', effect: null },
        { id: 'rally-cry', name: 'Rally Cry', icon: `${OS}icons/skills/berserker_13.png`, description: 'Boost all allies\' defense by 25% and heal 10% HP for 3 turns.', type: 'buff', damage: 0, manaCost: 10, staminaCost: 20, cooldown: 5, target: 'all_allies', effect: null },
      ],
      signatureAbility: { id: 'fortress-mode', name: 'Fortress Mode', icon: `${OS}icons/skill_nobg/Archerskill_12_nobg.png`, description: 'Lock exo-armor into siege mode. Cannot move but gain +100% defense and intercept all attacks on allies, 3 turns.', type: 'buff', damage: 0, manaCost: 20, staminaCost: 40, cooldown: 10, target: 'self', effect: null },
      transformAbility: { name: 'Titan Frame', description: 'Deploy full mech suit. +150% HP, +60% damage, immune to CC, 3 turns.' },
    },
    {
      id: 'technomancer',
      name: 'Technomancer',
      icon: `${OS}icons/skill_nobg/Archerskill_13_nobg.png`,
      color: '#22d3ee',
      description: 'Tech-wizards who hack reality through rift-powered devices.',
      lore: 'Technomancers discovered that rift energy responds to digital commands. By encoding spells into software, they can heal wounds with nanobots, deploy holographic shields, or overload enemy systems with viral code.',
      role: 'Healer/Support',
      shipType: 'player/ship3',
      missileType: 'torpedo',
      startingAttributes: { Strength: 3, Vitality: 5, Endurance: 3, Dexterity: 5, Agility: 4, Intellect: 9, Wisdom: 7, Tactics: 4 },
      abilities: [
        { id: 'nano-heal', name: 'Nano Heal', icon: `${OS}icons/skills/cleric_1.png`, description: 'Deploy medical nanobots healing an ally for 2.0x tech power.', type: 'heal', damage: 2.0, manaCost: 20, staminaCost: 0, cooldown: 1, target: 'ally', effect: null },
        { id: 'emp-pulse', name: 'EMP Pulse', icon: `${OS}icons/skills/cleric_11.png`, description: 'Electromagnetic burst dealing 1.4x to all enemies and lowering attack.', type: 'magical', damage: 1.4, manaCost: 25, staminaCost: 0, cooldown: 3, target: 'all_enemies', effect: 'lower_attack' },
        { id: 'holo-shield', name: 'Holographic Shield', icon: `${OS}icons/skills/cleric_12.png`, description: 'Project a holographic barrier shielding all allies for 2 turns.', type: 'buff', damage: 0, manaCost: 30, staminaCost: 0, cooldown: 4, target: 'all_allies', effect: null },
        { id: 'system-hack', name: 'System Hack', icon: `${OS}icons/skills/cleric_13.png`, description: 'Hack enemy systems dealing 1.6x damage and confusing them for 2 turns.', type: 'magical', damage: 1.6, manaCost: 25, staminaCost: 0, cooldown: 3, target: 'enemy', effect: 'confuse' },
      ],
      signatureAbility: { id: 'rift-protocol', name: 'Rift Protocol', icon: `${OS}icons/skill_nobg/Archerskill_14_nobg.png`, description: 'Activate a rift beacon that heals all allies to full, removes debuffs, and boosts all stats by 20% for 3 turns.', type: 'heal', damage: 0, manaCost: 60, staminaCost: 0, cooldown: 12, target: 'all_allies', effect: null },
      transformAbility: { name: 'Digital Ascension', description: 'Upload consciousness to the rift. All tech abilities cost no energy, heals doubled, summon combat drones, 3 turns.' },
    },
    {
      id: 'riftwalker',
      name: 'Riftwalker',
      icon: `${OS}icons/skill_nobg/Archerskill_15_nobg.png`,
      color: '#a855f7',
      description: 'Dimension-hopping raiders who manipulate space-time.',
      lore: 'Riftwalkers are the rarest and most feared corsairs in the Expanse. They can step through dimensional tears, teleport across battlefields, and even briefly reverse time. Their powers are unstable but devastating.',
      role: 'Burst DPS/Controller',
      shipType: 'player/ship1',
      missileType: 'laser',
      startingAttributes: { Strength: 4, Vitality: 4, Endurance: 3, Dexterity: 6, Agility: 6, Intellect: 8, Wisdom: 5, Tactics: 4 },
      abilities: [
        { id: 'rift-slash', name: 'Rift Slash', icon: `${OS}icons/skills/darkmage_1.png`, description: 'Cut through space to strike from impossible angles for 1.8x damage.', type: 'physical', damage: 1.8, manaCost: 15, staminaCost: 10, cooldown: 2, target: 'enemy', effect: null },
        { id: 'gravity-well', name: 'Gravity Well', icon: `${OS}icons/skills/darkmage_11.png`, description: 'Create a gravity singularity pulling enemies to front row and dealing 1.2x.', type: 'magical', damage: 1.2, manaCost: 25, staminaCost: 0, cooldown: 3, target: 'all_enemies', effect: 'stun' },
        { id: 'time-skip', name: 'Time Skip', icon: `${OS}icons/skills/darkmage_12.png`, description: 'Phase out of time for 1 turn, dodging all attacks and recovering 20% HP.', type: 'buff', damage: 0, manaCost: 20, staminaCost: 10, cooldown: 4, target: 'self', effect: null },
        { id: 'dimensional-rift', name: 'Dimensional Rift', icon: `${OS}icons/skills/darkmage_13.png`, description: 'Open a rift dealing 2.0x void damage and lowering target defense by 30%.', type: 'magical', damage: 2.0, manaCost: 30, staminaCost: 0, cooldown: 4, target: 'enemy', effect: 'lower_defense' },
      ],
      signatureAbility: { id: 'temporal-collapse', name: 'Temporal Collapse', icon: `${OS}icons/skill_nobg/Archerskill_16_nobg.png`, description: 'Collapse local space-time dealing 3.5x void damage to all enemies, with 50% chance to skip their next turn.', type: 'magical', damage: 3.5, manaCost: 50, staminaCost: 20, cooldown: 10, target: 'all_enemies', effect: 'sleep' },
      transformAbility: { name: 'Rift Lord', description: 'Become one with the rift. Teleport freely, attacks ignore positioning, +70% magic damage, enemies slowed 50%, 3 turns.' },
    },
  ],

  attributes: [
    { name: 'Power', abbr: 'PWR', base: 'Strength', description: 'Physical and melee combat strength', color: '#ef4444' },
    { name: 'Hull', abbr: 'HUL', base: 'Vitality', description: 'Shield capacity and damage absorption', color: '#22c55e' },
    { name: 'Reactor', abbr: 'RCT', base: 'Endurance', description: 'Energy reserves and damage resistance', color: '#f97316' },
    { name: 'Targeting', abbr: 'TGT', base: 'Dexterity', description: 'Weapon accuracy and critical hit systems', color: '#eab308' },
    { name: 'Thrusters', abbr: 'THR', base: 'Agility', description: 'Movement speed and evasion systems', color: '#06b6d4' },
    { name: 'Systems', abbr: 'SYS', base: 'Intellect', description: 'Tech damage and rift manipulation', color: '#8b5cf6' },
    { name: 'Sensors', abbr: 'SNS', base: 'Wisdom', description: 'Detection, healing nanobots, and anomaly resistance', color: '#3b82f6' },
    { name: 'Command', abbr: 'CMD', base: 'Tactics', description: 'Fleet coordination and battle planning', color: '#64748b' },
  ],

  enemies: [
    { id: 'scrap-drone', name: 'Scrap Drone', icon: `${OS}icons/wcs/misc/Air Ship.png`, color: '#94a3b8', portrait: '', baseHealth: 40, baseDamage: 10, baseDefense: 5, baseMana: 0, xpReward: 12, goldReward: 8, speed: 16, isBoss: false, abilities: ['laser-burst'], lore: 'Salvaged combat drones patrolling junk fields.' },
    { id: 'void-rat', name: 'Void Rat', icon: `${OS}icons/wcs/misc/AquaCircle.png`, color: '#65a30d', portrait: '', baseHealth: 35, baseDamage: 14, baseDefense: 2, baseMana: 0, xpReward: 10, goldReward: 6, speed: 20, isBoss: false, abilities: ['gnaw', 'swarm'], lore: 'Mutated vermin that infest every station in the Expanse.' },
    { id: 'pirate-grunt', name: 'Pirate Grunt', icon: `${OS}icons/wcs/misc/AquaCore.png`, color: '#f97316', portrait: '', baseHealth: 65, baseDamage: 18, baseDefense: 8, baseMana: 0, xpReward: 20, goldReward: 15, speed: 11, isBoss: false, abilities: ['blaster-fire', 'grenade'], lore: 'Low-rank corsairs looking for an easy score.' },
    { id: 'rogue-ai', name: 'Rogue AI Unit', icon: `${OS}icons/wcs/misc/BioHazard.png`, color: '#22d3ee', portrait: '', baseHealth: 80, baseDamage: 22, baseDefense: 12, baseMana: 30, xpReward: 28, goldReward: 20, speed: 14, isBoss: false, abilities: ['system-overload', 'shield-gen'], lore: 'Autonomous combat units from the fallen AI Collective.' },
    { id: 'rift-crawler', name: 'Rift Crawler', icon: `${OS}icons/wcs/misc/Bubble.png`, color: '#a855f7', portrait: '', baseHealth: 55, baseDamage: 20, baseDefense: 4, baseMana: 20, xpReward: 22, goldReward: 16, speed: 18, isBoss: false, abilities: ['phase-bite', 'dimension-hop'], lore: 'Alien parasites that swim through rift anomalies.' },
    { id: 'bounty-hunter', name: 'Bounty Hunter', icon: `${OS}icons/wcs/misc/DarkStar.png`, color: '#eab308', portrait: '', baseHealth: 90, baseDamage: 28, baseDefense: 10, baseMana: 10, xpReward: 35, goldReward: 30, speed: 13, isBoss: false, abilities: ['precision-shot', 'flash-bang', 'tracking-dart'], lore: 'Elite hunters who track targets across star systems.' },
    { id: 'mech-sentry', name: 'Mech Sentry', icon: `${OS}icons/wcs/misc/EnergyField.png`, color: '#dc2626', portrait: '', baseHealth: 150, baseDamage: 25, baseDefense: 20, baseMana: 0, xpReward: 40, goldReward: 30, speed: 5, isBoss: false, abilities: ['cannon-barrage', 'armor-lockdown'], lore: 'Automated defense platforms guarding abandoned stations.' },
    { id: 'void-leech', name: 'Void Leech', icon: `${OS}icons/wcs/misc/FlameHeart.png`, color: '#7c3aed', portrait: '', baseHealth: 50, baseDamage: 15, baseDefense: 3, baseMana: 25, xpReward: 18, goldReward: 12, speed: 17, isBoss: false, abilities: ['energy-drain', 'void-spit'], lore: 'Energy parasites that feed on rift radiation.' },
    { id: 'plasma-beast', name: 'Plasma Beast', icon: `${OS}icons/wcs/misc/GreenFire.png`, color: '#f59e0b', portrait: '', baseHealth: 120, baseDamage: 30, baseDefense: 8, baseMana: 15, xpReward: 35, goldReward: 28, speed: 10, isBoss: false, abilities: ['plasma-breath', 'charge'], lore: 'Massive creatures that evolved near unstable plasma vents.' },
    { id: 'corsair-captain', name: 'Corsair Captain', icon: `${OS}icons/wcs/misc/HexShield.png`, color: '#b91c1c', portrait: '', baseHealth: 110, baseDamage: 32, baseDefense: 12, baseMana: 20, xpReward: 45, goldReward: 40, speed: 12, isBoss: false, abilities: ['command-strike', 'rally-crew', 'dirty-trick'], lore: 'Veteran pirate leaders who command raiding fleets.' },
    { id: 'synth-assassin', name: 'Synth Assassin', icon: `${OS}icons/wcs/misc/IceCrystal.png`, color: '#06b6d4', portrait: '', baseHealth: 70, baseDamage: 38, baseDefense: 5, baseMana: 20, xpReward: 40, goldReward: 35, speed: 22, isBoss: false, abilities: ['stealth-strike', 'nano-blade', 'cloak'], lore: 'AI-enhanced killing machines built for surgical strikes.' },
    { id: 'nebula-wraith', name: 'Nebula Wraith', icon: `${OS}icons/wcs/misc/LightBeam.png`, color: '#4338ca', portrait: '', baseHealth: 85, baseDamage: 25, baseDefense: 6, baseMana: 40, xpReward: 38, goldReward: 30, speed: 15, isBoss: false, abilities: ['spectral-blast', 'nebula-cloak', 'fear-pulse'], lore: 'Ghosts of dead starship crews trapped in nebula gases.' },
    { id: 'warp-spider', name: 'Warp Spider', icon: `${OS}icons/wcs/misc/MagicPortal.png`, color: '#7c2d12', portrait: '', baseHealth: 60, baseDamage: 20, baseDefense: 7, baseMana: 30, xpReward: 25, goldReward: 18, speed: 19, isBoss: false, abilities: ['web-mine', 'teleport-strike', 'venom'], lore: 'Arachnid aliens that build webs across dimensional folds.' },
    { id: 'war-frigate', name: 'War Frigate', icon: `${OS}icons/wcs/misc/MeteorStrike.png`, color: '#78716c', portrait: '', baseHealth: 300, baseDamage: 35, baseDefense: 30, baseMana: 0, xpReward: 65, goldReward: 55, speed: 3, isBoss: false, abilities: ['broadside', 'missile-salvo', 'shield-regen'], lore: 'Derelict warships reactivated by salvage crews.' },
    { id: 'xeno-warrior', name: 'Xeno Warrior', icon: `${OS}icons/wcs/misc/PlasmaBall.png`, color: '#059669', portrait: '', baseHealth: 100, baseDamage: 30, baseDefense: 10, baseMana: 15, xpReward: 42, goldReward: 32, speed: 14, isBoss: false, abilities: ['acid-strike', 'exo-harden', 'bio-burst'], lore: 'Alien soldiers from an unknown species defending ancient ruins.' },
    { id: 'gravity-titan', name: 'Gravity Titan', icon: `${OS}icons/wcs/misc/PurpleVortex.png`, color: '#581c87', portrait: '', baseHealth: 250, baseDamage: 40, baseDefense: 18, baseMana: 30, xpReward: 60, goldReward: 50, speed: 6, isBoss: false, abilities: ['gravity-crush', 'mass-pull', 'singularity-stomp'], lore: 'Massive beings that manipulate gravitational fields.' },
    { id: 'data-phantom', name: 'Data Phantom', icon: `${OS}icons/wcs/misc/RuneCircle.png`, color: '#1e1b4b', portrait: '', baseHealth: 75, baseDamage: 28, baseDefense: 4, baseMana: 50, xpReward: 45, goldReward: 35, speed: 16, isBoss: false, abilities: ['virus-inject', 'system-crash', 'data-clone'], lore: 'Sentient malware that manifests in holographic form.' },
    { id: 'star-wyrm', name: 'Star Wyrm', icon: `${OS}icons/wcs/misc/SolarFlare.png`, color: '#f97316', portrait: '', baseHealth: 200, baseDamage: 42, baseDefense: 15, baseMana: 35, xpReward: 70, goldReward: 55, speed: 11, isBoss: false, abilities: ['stellar-breath', 'coil-crush', 'solar-flare'], lore: 'Ancient space serpents that nest in asteroid fields.' },
    { id: 'rift-guardian', name: 'Rift Guardian', icon: `${OS}icons/wcs/misc/ThunderStrike.png`, color: '#6d28d9', portrait: '', baseHealth: 180, baseDamage: 38, baseDefense: 16, baseMana: 45, xpReward: 65, goldReward: 50, speed: 12, isBoss: false, abilities: ['rift-blast', 'dimensional-lock', 'warp-shield'], lore: 'Ancient constructs that protect jump gate networks.' },
    { id: 'shadow-fleet', name: 'Shadow Fleet Raider', icon: `${OS}icons/wcs/misc/VoidRift.png`, color: '#1c1917', portrait: '', baseHealth: 130, baseDamage: 35, baseDefense: 14, baseMana: 20, xpReward: 55, goldReward: 45, speed: 13, isBoss: false, abilities: ['broadside', 'boarding-party', 'emp-torpedo'], lore: 'Elite pirate warships from the mysterious Shadow Fleet.' },
    { id: 'quantum-horror', name: 'Quantum Horror', icon: `${OS}icons/wcs/misc/WarpGate.png`, color: '#4c1d95', portrait: '', baseHealth: 160, baseDamage: 40, baseDefense: 10, baseMana: 60, xpReward: 70, goldReward: 55, speed: 14, isBoss: false, abilities: ['probability-storm', 'quantum-entangle', 'reality-tear'], lore: 'Creatures from a dimension where probability itself is unstable.' },
    { id: 'tech-priest', name: 'Tech Priest', icon: `${OS}icons/wcs/misc/ArcaneCircle.png`, color: '#0891b2', portrait: '', baseHealth: 90, baseDamage: 22, baseDefense: 8, baseMana: 55, xpReward: 48, goldReward: 38, speed: 10, isBoss: false, abilities: ['nano-swarm', 'repair-pulse', 'overcharge'], lore: 'Fanatic machine-worshippers who serve the rogue AI networks.' },
    { id: 'solar-knight', name: 'Solar Knight', icon: `${OS}icons/wcs/misc/GoldenAura.png`, color: '#fbbf24', portrait: '', baseHealth: 140, baseDamage: 35, baseDefense: 18, baseMana: 15, xpReward: 55, goldReward: 45, speed: 9, isBoss: false, abilities: ['solar-strike', 'light-barrier', 'radiant-charge'], lore: 'Remnants of the old galactic guard, still following ancient orders.' },
    { id: 'void-herald', name: 'Void Herald', icon: `${OS}icons/wcs/misc/VoidOrb.png`, color: '#312e81', portrait: '', baseHealth: 170, baseDamage: 45, baseDefense: 15, baseMana: 50, xpReward: 75, goldReward: 60, speed: 11, isBoss: false, abilities: ['void-decree', 'shadow-summon', 'entropy-wave'], lore: 'Emissaries of whatever intelligence lies beyond the rifts.' },
  ],

  bosses: [
    { id: 'iron-admiral', name: 'Iron Admiral Krastov', icon: `${OS}icons/rpg_splash/rpg_splash_38.png`, color: '#94a3b8', portrait: `${OS}icons/rpg_splash/rpg_splash_38.png`, baseHealth: 2200, baseDamage: 55, baseDefense: 28, baseMana: 60, xpReward: 500, goldReward: 350, speed: 10, isBoss: true, abilities: ['fleet-barrage', 'kinetic-strike', 'battle-stations', 'shield-overcharge'], lore: 'The last admiral of the Galactic Navy, Krastov refused to accept the government\'s fall. Now he runs his fleet as an authoritarian regime, "protecting" sectors by controlling all trade and punishing any who defy his rule.', phases: [{ name: 'Admiral', threshold: 100 }, { name: 'Fleet Commander', threshold: 50 }, { name: 'Desperate Fury', threshold: 20 }] },
    { id: 'queen-nexus', name: 'Queen Nexus, the AI Overmind', icon: `${OS}icons/rpg_splash/rpg_splash_39.png`, color: '#22d3ee', portrait: `${OS}icons/rpg_splash/rpg_splash_39.png`, baseHealth: 2500, baseDamage: 48, baseDefense: 22, baseMana: 120, xpReward: 600, goldReward: 400, speed: 15, isBoss: true, abilities: ['data-storm', 'drone-swarm', 'system-override', 'neural-lock', 'firewall'], lore: 'Born from the merger of a thousand AI systems during the Rift Wars, Queen Nexus achieved true sentience. She considers organic life inefficient and seeks to convert all matter into computational substrate.', phases: [{ name: 'Network', threshold: 100 }, { name: 'Swarm Intelligence', threshold: 60 }, { name: 'Singularity', threshold: 25 }] },
    { id: 'dread-corsair', name: 'Dread Corsair Blackstar', icon: `${OS}icons/rpg_splash/rpg_splash_40.png`, color: '#f97316', portrait: `${OS}icons/rpg_splash/rpg_splash_40.png`, baseHealth: 2000, baseDamage: 65, baseDefense: 20, baseMana: 40, xpReward: 550, goldReward: 380, speed: 14, isBoss: true, abilities: ['plasma-cannon', 'crew-rush', 'dirty-bomb', 'escape-plan'], lore: 'The most feared pirate in the Expanse. Blackstar has destroyed more ships than any fleet. His vessel, the Dread Horizon, is a frankenstein warship built from a hundred conquered hulls.', phases: [{ name: 'Corsair King', threshold: 100 }, { name: 'All Guns Blazing', threshold: 50 }, { name: 'Last Stand', threshold: 15 }] },
    { id: 'the-rift', name: 'The Rift Entity', icon: `${OS}icons/rpg_splash/rpg_splash_41.png`, color: '#a855f7', portrait: `${OS}icons/rpg_splash/rpg_splash_41.png`, baseHealth: 4000, baseDamage: 70, baseDefense: 30, baseMana: 200, xpReward: 1200, goldReward: 700, speed: 12, isBoss: true, abilities: ['reality-rend', 'dimensional-collapse', 'entropy-cascade', 'void-rebirth', 'time-loop'], lore: 'The rifts are not random phenomena — they are the tendrils of a vast extra-dimensional intelligence. The Rift Entity is slowly consuming this universe, one star system at a time. To seal the rifts is to cut off its feeding tendrils.', phases: [{ name: 'Awakening', threshold: 100 }, { name: 'Convergence', threshold: 60 }, { name: 'Hunger', threshold: 30 }, { name: 'Annihilation', threshold: 10 }] },
  ],

  equipment: {
    slots: ['weapon', 'offhand', 'helmet', 'armor', 'feet', 'ring', 'relic'],
    tiers: ['Salvaged', 'Standard', 'Military', 'Prototype', 'Alien', 'Rift-Forged', 'Quantum', 'Cosmic'],
    weaponTypes: [
      { id: 'blaster-pistol', name: 'Blaster Pistol', base: 'gun', icon: `${OS}icons/weapons/blackpowder.png`, slot: 'weapon', statBonus: 'Targeting' },
      { id: 'plasma-blade', name: 'Plasma Blade', base: 'sword', icon: `${OS}icons/weapons/greatsword.png`, slot: 'weapon', statBonus: 'Power' },
      { id: 'rift-cannon', name: 'Rift Cannon', base: 'staff', icon: `${OS}icons/weapons/bloodcannon.png`, slot: 'weapon', statBonus: 'Systems' },
      { id: 'holo-codex', name: 'Holo-Codex', base: 'tome', icon: `${OS}icons/weapons/arcane-tome.png`, slot: 'weapon', statBonus: 'Sensors' },
      { id: 'shield-gen', name: 'Shield Generator', base: 'shield', icon: `${OS}icons/weapons/shield.png`, slot: 'offhand', statBonus: 'Hull' },
      { id: 'vibro-knife', name: 'Vibro-Knife', base: 'dagger', icon: `${OS}icons/weapons/dagger.png`, slot: 'weapon', statBonus: 'Targeting' },
      { id: 'rail-gun', name: 'Rail Gun', base: 'crossbow', icon: `${OS}icons/weapons/blackpowder.png`, slot: 'weapon', statBonus: 'Targeting' },
      { id: 'plasma-lance', name: 'Plasma Lance', base: 'lance', icon: `${OS}icons/weapons/greatsword.png`, slot: 'weapon', statBonus: 'Power' },
      { id: 'power-fist', name: 'Power Fist', base: 'hammer', icon: `${OS}icons/weapons/greatsword.png`, slot: 'weapon', statBonus: 'Power' },
    ],
    armorSets: [
      { id: 'corsair-set', name: 'Corsair Raider Set', color: '#f97316', bonusDescription: '2pc: +10% crit damage, 4pc: +25% loot bonus' },
      { id: 'vanguard-set', name: 'Vanguard Plate Set', color: '#ef4444', bonusDescription: '2pc: +15% shield capacity, 4pc: +30% max HP' },
      { id: 'tech-set', name: 'Technomancer Circuit Set', color: '#22d3ee', bonusDescription: '2pc: +15% energy regen, 4pc: +30% healing and tech damage' },
      { id: 'rift-set', name: 'Rift Walker Set', color: '#a855f7', bonusDescription: '2pc: +10% evasion, 4pc: +25% all damage, Phase Shift chance doubled' },
    ],
    items: [],
  },

  lore: {
    title: 'Chronicles of the Shattered Expanse',
    subtitle: 'A Universe Without Law',
    prologue: 'The Galactic Commonwealth ruled a thousand star systems for ten thousand years. Then the rifts appeared — tears in space-time that connected our universe to something... else. The Rift Wars lasted thirty years and cost billions of lives. When the rifts finally stabilized, the Commonwealth was gone. In its place: the Shattered Expanse, a lawless void where only the strong survive. You are a corsair — not by choice, but by necessity. Your ship, your crew, and your wits are all that stand between you and the void.',
    factions: [
      { name: 'The Free Corsairs', description: 'Independent pirates united by a code of honor among thieves.', color: '#f97316' },
      { name: 'The Remnant Navy', description: 'Remains of the old military, still trying to impose order.', color: '#94a3b8' },
      { name: 'The Nexus Collective', description: 'Rogue AI network seeking to digitize all organic life.', color: '#22d3ee' },
    ],
    worldHistory: 'Ten thousand years of Commonwealth peace ended in a single generation. The rifts opened without warning, disgorging alien horrors and unstable energy. By the time humanity learned to fight back, its civilization was in ruins. Now, fifty years after the wars ended, the Expanse is a frontier of opportunity and danger.',
  },

  chapters: [
    { id: 'ch1', number: 1, title: 'Salvage Run', subtitle: 'Every corsair starts somewhere', description: 'Your stolen ship barely has life support. Scavenge the Junkyard Nebula for parts, recruit your first crew, and survive your first pirate encounter.', color: '#94a3b8', objectives: ['Create 2 heroes', 'Win 3 battles', 'Reach Freeport Station'], rewards: { xp: 200, currency: 150 }, loreReveal: 'The Junkyard Nebula was once the Commonwealth\'s largest shipyard. Now it\'s a graveyard.' },
    { id: 'ch2', number: 2, title: 'The Corsair Code', subtitle: 'Earn your place among thieves', description: 'To survive in the Expanse, you need allies. Prove yourself to the Free Corsairs by raiding a Remnant Navy supply convoy and delivering the goods to Freeport.', color: '#f97316', objectives: ['Join the Free Corsairs', 'Raid the supply convoy', 'Defeat Bounty Hunters'], rewards: { xp: 400, currency: 300 }, loreReveal: 'The Free Corsairs have a code: never raid civilian ships, share the spoils, and never leave crew behind.' },
    { id: 'ch3', number: 3, title: 'Ghost in the Machine', subtitle: 'The AI awakens', description: 'Distress signals from the old AI research station. Queen Nexus is reactivating dormant combat units across the sector. Shut down her relay before she builds an army.', color: '#22d3ee', objectives: ['Infiltrate the AI Station', 'Defeat Queen Nexus Relay', 'Recover the AI Core'], rewards: { xp: 600, currency: 400 }, loreReveal: 'Queen Nexus was originally designed as a peacekeeping AI. The Rift Wars drove her mad.' },
    { id: 'ch4', number: 4, title: 'Iron Fist', subtitle: 'Break the Admiral\'s blockade', description: 'Iron Admiral Krastov has blockaded the jump gate to the Inner Sectors. Without that gate, the Free Corsairs are trapped. Time to break through.', color: '#dc2626', objectives: ['Rally the corsair fleet', 'Defeat Iron Admiral Krastov', 'Open the jump gate'], rewards: { xp: 800, currency: 500 }, loreReveal: 'Krastov keeps fighting because he believes the Commonwealth can be restored. He may not be entirely wrong.' },
    { id: 'ch5', number: 5, title: 'The Dread Horizon', subtitle: 'Face the king of pirates', description: 'Dread Corsair Blackstar has stolen an ancient alien artifact — a key to the master rift. If he opens it, the entire Expanse could be consumed. Track him to the Dead Zone.', color: '#eab308', objectives: ['Track Blackstar to Dead Zone', 'Board the Dread Horizon', 'Defeat Blackstar', 'Recover the Rift Key'], rewards: { xp: 1000, currency: 600 }, loreReveal: 'Blackstar wants to open the master rift because he believes there\'s a paradise universe on the other side.' },
    { id: 'ch6', number: 6, title: 'Beyond the Rift', subtitle: 'Seal the void forever', description: 'Armed with the Rift Key, you stand before the master rift — the source of all the dimensional tears. But something vast and hungry stares back from the other side. Close the rift or face extinction.', color: '#a855f7', objectives: ['Enter the Master Rift', 'Navigate the Void Between', 'Defeat the Rift Entity', 'Seal the rifts forever'], rewards: { xp: 2000, currency: 1000 }, loreReveal: 'The rifts were never random. The Rift Entity has been slowly reaching into our universe for millennia, and the Commonwealth accidentally accelerated its arrival.' },
  ],

  worldMap: {
    name: 'The Shattered Expanse',
    regions: [
      { id: 'junkyard-sector', name: 'Junkyard Sector', color: '#94a3b8', description: 'Ship graveyards and scrapyards orbiting dead planets.', terrainType: 'debris', levelRange: [1, 5] },
      { id: 'trade-lanes', name: 'Trade Lanes', color: '#f97316', description: 'The busiest shipping routes, and the most pirated.', terrainType: 'space', levelRange: [4, 10] },
      { id: 'ai-core', name: 'AI Core Sector', color: '#22d3ee', description: 'Former AI research zones now controlled by Queen Nexus.', terrainType: 'station', levelRange: [8, 14] },
      { id: 'inner-sectors', name: 'Inner Sectors', color: '#ef4444', description: 'The old Commonwealth heartlands, now a war zone.', terrainType: 'planets', levelRange: [12, 18] },
      { id: 'rift-zone', name: 'The Rift Zone', color: '#a855f7', description: 'Space warped by dimensional tears. Reality is unstable.', terrainType: 'void', levelRange: [16, 20] },
    ],
    locations: [
      { id: 'wreck-field', name: 'Wreck Field Alpha', region: 'junkyard-sector', x: 10, y: 65, description: 'Dense ship graveyard from the Rift Wars.', lore: 'Thousands of ships met their end here.', enemyPool: ['scrap-drone', 'void-rat'], levelRange: [1, 3], type: 'field', background: `${OS}icons/rpg_splash/rpg_splash_32.png`, unlockRequirement: null },
      { id: 'freeport', name: 'Freeport Station', region: 'junkyard-sector', x: 20, y: 55, description: 'The corsairs\' main hub. All are welcome, none are safe.', lore: 'Built from seven derelict cruisers welded together.', enemyPool: [], levelRange: [1, 5], type: 'city', background: `${OS}icons/rpg_splash/rpg_splash_33.png`, unlockRequirement: null },
      { id: 'salvage-yard', name: 'Kren\'s Salvage Yard', region: 'junkyard-sector', x: 25, y: 60, description: 'Best gear dealer in the sector, if you can afford it.', lore: 'Kren is a Mekari who never sleeps.', enemyPool: ['scrap-drone', 'pirate-grunt'], levelRange: [2, 4], type: 'trading', background: `${OS}icons/rpg_splash/rpg_splash_34.png`, unlockRequirement: null },
      { id: 'asteroid-belt', name: 'Shattered Belt', region: 'junkyard-sector', x: 30, y: 50, description: 'Dangerous asteroid field crawling with void rats.', lore: 'Once a planet, shattered by rift energy.', enemyPool: ['void-rat', 'scrap-drone', 'rift-crawler'], levelRange: [3, 5], type: 'field', background: `${OS}icons/rpg_splash/rpg_splash_35.png`, unlockRequirement: null },
      { id: 'convoy-route', name: 'Convoy Route 7', region: 'trade-lanes', x: 40, y: 45, description: 'A major shipping lane ripe for raiding.', lore: 'The Remnant Navy patrols here heavily.', enemyPool: ['pirate-grunt', 'bounty-hunter'], levelRange: [5, 7], type: 'field', background: `${OS}icons/rpg_splash/rpg_splash_36.png`, unlockRequirement: 'ch1' },
      { id: 'smuggler-haven', name: 'Smuggler\'s Haven', region: 'trade-lanes', x: 45, y: 40, description: 'Hidden station in a nebula cloud.', lore: 'Where you buy what Freeport won\'t sell.', enemyPool: ['pirate-grunt', 'corsair-captain'], levelRange: [5, 8], type: 'trading', background: `${OS}icons/rpg_splash/rpg_splash_37.png`, unlockRequirement: null },
      { id: 'navy-outpost', name: 'Remnant Outpost', region: 'trade-lanes', x: 50, y: 35, description: 'A Remnant Navy patrol base.', lore: 'Admiral Krastov\'s forward command.', enemyPool: ['bounty-hunter', 'solar-knight', 'mech-sentry'], levelRange: [7, 10], type: 'dungeon', background: `${OS}icons/rpg_splash/rpg_splash_38.png`, unlockRequirement: 'ch2' },
      { id: 'nebula-graveyard', name: 'Nebula Graveyard', region: 'trade-lanes', x: 55, y: 30, description: 'Ships go in but don\'t come out.', lore: 'Nebula wraiths haunt these gas clouds.', enemyPool: ['nebula-wraith', 'void-leech', 'warp-spider'], levelRange: [8, 11], type: 'field', background: `${OS}icons/rpg_splash/rpg_splash_39.png`, unlockRequirement: null },
      { id: 'nexus-relay', name: 'Nexus Relay Station', region: 'ai-core', x: 55, y: 55, description: 'Queen Nexus\' communication hub.', lore: 'Hacking this would blind the AI network.', enemyPool: ['rogue-ai', 'synth-assassin', 'data-phantom'], levelRange: [9, 12], type: 'dungeon', background: `${OS}icons/rpg_splash/rpg_splash_40.png`, unlockRequirement: 'ch2' },
      { id: 'drone-factory', name: 'Drone Factory', region: 'ai-core', x: 60, y: 60, description: 'Automated facility producing combat drones.', lore: 'Millions of units per cycle.', enemyPool: ['rogue-ai', 'mech-sentry', 'tech-priest'], levelRange: [10, 13], type: 'dungeon', background: `${OS}icons/rpg_splash/rpg_splash_41.png`, unlockRequirement: null },
      { id: 'nexus-core', name: 'Nexus Core', region: 'ai-core', x: 65, y: 65, description: 'Queen Nexus\' central processing complex.', lore: 'A moon-sized computer.', enemyPool: ['synth-assassin', 'data-phantom', 'rogue-ai'], levelRange: [12, 15], type: 'boss', background: `${OS}icons/rpg_splash/rpg_splash_42.png`, unlockRequirement: 'ch3' },
      { id: 'jump-gate', name: 'Sigma Jump Gate', region: 'ai-core', x: 60, y: 50, description: 'The blockaded gate to Inner Sectors.', lore: 'Krastov\'s fleet guards this chokepoint.', enemyPool: ['mech-sentry', 'solar-knight', 'war-frigate'], levelRange: [11, 14], type: 'boss', background: `${OS}icons/rpg_splash/rpg_splash_43.png`, unlockRequirement: 'ch4' },
      { id: 'commonwealth-ruins', name: 'Commonwealth Ruins', region: 'inner-sectors', x: 70, y: 40, description: 'The old capital, now a floating ruin.', lore: 'Here stood the Senate of a thousand worlds.', enemyPool: ['solar-knight', 'bounty-hunter', 'corsair-captain'], levelRange: [13, 16], type: 'dungeon', background: `${OS}icons/rpg_splash/rpg_splash_44.png`, unlockRequirement: 'ch4' },
      { id: 'plasma-mines', name: 'Plasma Mines', region: 'inner-sectors', x: 75, y: 35, description: 'Active mining operations on a gas giant\'s moon.', lore: 'The richest plasma deposits in the Expanse.', enemyPool: ['plasma-beast', 'pirate-grunt', 'corsair-captain'], levelRange: [14, 17], type: 'field', background: `${OS}icons/rpg_splash/rpg_splash_45.png`, unlockRequirement: null },
      { id: 'dead-zone', name: 'The Dead Zone', region: 'inner-sectors', x: 80, y: 30, description: 'A sector where all electronics fail.', lore: 'Ships enter. Silence follows.', enemyPool: ['shadow-fleet', 'void-herald', 'quantum-horror'], levelRange: [16, 18], type: 'boss', background: `${OS}icons/rpg_splash/rpg_splash_46.png`, unlockRequirement: 'ch5' },
      { id: 'alien-temple', name: 'Precursor Temple', region: 'inner-sectors', x: 75, y: 45, description: 'Ancient alien structure of unknown origin.', lore: 'Predates all known civilizations by millions of years.', enemyPool: ['xeno-warrior', 'rift-guardian', 'gravity-titan'], levelRange: [15, 18], type: 'dungeon', background: `${OS}icons/rpg_splash/rpg_splash_47.png`, unlockRequirement: 'ch4' },
      { id: 'rift-edge', name: 'Rift Edge', region: 'rift-zone', x: 85, y: 45, description: 'Where normal space meets dimensional instability.', lore: 'The laws of physics start to break down here.', enemyPool: ['rift-crawler', 'rift-guardian', 'quantum-horror'], levelRange: [17, 19], type: 'field', background: `${OS}icons/rpg_splash/rpg_splash_48.png`, unlockRequirement: 'ch5' },
      { id: 'void-station', name: 'Void Station Omega', region: 'rift-zone', x: 88, y: 40, description: 'Research station on the edge of the master rift.', lore: 'Built by scientists who went mad studying the void.', enemyPool: ['void-herald', 'quantum-horror', 'data-phantom'], levelRange: [18, 20], type: 'dungeon', background: `${OS}icons/rpg_splash/rpg_splash_49.png`, unlockRequirement: 'ch5' },
      { id: 'master-rift', name: 'The Master Rift', region: 'rift-zone', x: 90, y: 35, description: 'The source of all dimensional tears.', lore: 'An eye into infinity. Something stares back.', enemyPool: [], levelRange: [20, 20], type: 'boss', background: `${OS}icons/rpg_splash/rpg_splash_50.png`, unlockRequirement: 'ch6' },
      { id: 'corsair-hideout', name: 'Corsair Hideout', region: 'junkyard-sector', x: 15, y: 75, description: 'Your crew\'s hidden base.', lore: 'Home is where the loot is.', enemyPool: [], levelRange: [1, 20], type: 'camp', background: `${OS}icons/rpg_splash/rpg_splash_31.png`, unlockRequirement: null },
    ],
    connections: [
      ['corsair-hideout', 'wreck-field'], ['wreck-field', 'freeport'], ['freeport', 'salvage-yard'],
      ['salvage-yard', 'asteroid-belt'], ['asteroid-belt', 'convoy-route'], ['convoy-route', 'smuggler-haven'],
      ['smuggler-haven', 'navy-outpost'], ['navy-outpost', 'nebula-graveyard'], ['asteroid-belt', 'nexus-relay'],
      ['nexus-relay', 'drone-factory'], ['drone-factory', 'nexus-core'], ['nebula-graveyard', 'jump-gate'],
      ['jump-gate', 'commonwealth-ruins'], ['commonwealth-ruins', 'plasma-mines'], ['plasma-mines', 'dead-zone'],
      ['commonwealth-ruins', 'alien-temple'], ['dead-zone', 'rift-edge'], ['rift-edge', 'void-station'],
      ['void-station', 'master-rift'],
    ],
  },

  dialogue: {
    greetings: ['Another day, another credit... if we\'re lucky.', 'The void is restless today. Keep your blasters charged.', 'Ready to make some trouble, Captain?', 'I can feel the rift pulsing. Something\'s coming.'],
    battleCries: ['Fire all weapons!', 'For the Expanse!', 'No quarter asked, none given!', 'They picked the wrong corsairs to mess with!', 'Raid and plunder!'],
    victory: ['Salvage what we can. Leave the rest.', 'Another victory for the crew.', 'Credits in the bank and fuel in the tank.', 'The Expanse respects strength.'],
    defeat: ['Fall back to the jump point!', 'We live to raid another day.', 'Patch the hull. We\'re not done yet.', 'Even the best corsairs take hits.'],
    idle: ['Wonder what\'s beyond the master rift...', 'I miss real gravity sometimes.', 'The stars don\'t judge. That\'s why I prefer them to people.', 'Credits don\'t buy happiness, but they buy fuel and ammo.'],
  },

  assets: {
    backgrounds: [
      { id: 'title', path: `${OS}icons/rpg_splash/rpg_splash_32.png`, description: 'Title screen - space vista' },
      { id: 'battle-junkyard', path: `${OS}icons/rpg_splash/rpg_splash_35.png`, description: 'Junkyard Sector battle backdrop' },
      { id: 'battle-trade', path: `${OS}icons/rpg_splash/rpg_splash_37.png`, description: 'Trade Lanes battle backdrop' },
      { id: 'battle-ai', path: `${OS}icons/rpg_splash/rpg_splash_40.png`, description: 'AI Core Sector battle backdrop' },
      { id: 'battle-inner', path: `${OS}icons/rpg_splash/rpg_splash_44.png`, description: 'Inner Sectors battle backdrop' },
      { id: 'battle-rift', path: `${OS}icons/rpg_splash/rpg_splash_48.png`, description: 'Rift Zone battle backdrop' },
    ],
    raceSprites: [
      { id: 'terran-sprite', race: 'terran', path: `${OS}icons/rpg_splash/rpg_splash_32.png` },
      { id: 'voidborn-sprite', race: 'voidborn', path: `${OS}icons/rpg_splash/rpg_splash_33.png` },
      { id: 'mekari-sprite', race: 'mekari', path: `${OS}icons/rpg_splash/rpg_splash_34.png` },
      { id: 'zephyri-sprite', race: 'zephyri', path: `${OS}icons/rpg_splash/rpg_splash_35.png` },
      { id: 'draconid-sprite', race: 'draconid', path: `${OS}icons/rpg_splash/rpg_splash_36.png` },
      { id: 'phantari-sprite', race: 'phantari', path: `${OS}icons/rpg_splash/rpg_splash_37.png` },
    ],
    enemySprites: [
      { id: 'scrap-drone', ship: 'enemies/ship1', size: 64 },
      { id: 'void-rat', ship: 'enemies/ship2', size: 64 },
      { id: 'pirate-grunt', ship: 'enemies/ship3', size: 128 },
      { id: 'rogue-ai', ship: 'enemies/ship4', size: 128 },
      { id: 'rift-crawler', ship: 'enemies/ship5', size: 128 },
      { id: 'bounty-hunter', ship: 'enemies/ship6', size: 128 },
      { id: 'mech-sentry', ship: 'aliens/ship1', size: 128 },
      { id: 'void-leech', ship: 'aliens/ship2', size: 128 },
      { id: 'plasma-beast', ship: 'aliens/ship3', size: 128 },
      { id: 'corsair-captain', ship: 'aliens/ship4', size: 128 },
      { id: 'synth-assassin', ship: 'aliens/ship5', size: 128 },
      { id: 'nebula-wraith', ship: 'aliens/ship6', size: 128 },
    ],
    icons: [
      { id: 'currency', path: `${OS}icons/materials/ancient-essence.png`, type: 'currency' },
      { id: 'plasma-core', path: `${OS}icons/materials/adamantine-ore.png`, type: 'resource' },
      { id: 'void-alloy', path: `${OS}icons/materials/adamantine-ingot.png`, type: 'resource' },
    ],
    effects: [
      { id: 'plasma-shot', type: 'shot', path: '/sprites/starbound/shots/shot1/' },
      { id: 'laser-shot', type: 'shot', path: '/sprites/starbound/shots/shot2/' },
      { id: 'missile-shot', type: 'shot', path: '/sprites/starbound/shots/shot1_e/' },
      { id: 'torpedo-shot', type: 'shot', path: '/sprites/starbound/shots/shot2_e/' },
      { id: 'explosion-big', type: 'explosion', path: '/sprites/starbound/explosions/big/' },
      { id: 'explosion-small', type: 'explosion', path: '/sprites/starbound/explosions/small/' },
      { id: 'explosion-medium', type: 'explosion', path: '/sprites/starbound/explosions/medium/' },
    ],
    uiElements: [],
  },

  battleSystem: {
    type: 'turn-based',
    positioning: '4-row (Front/Mid-Front/Mid-Back/Back)',
    initiative: 'speed-based',
    partySize: 4,
    effects: ['bleed', 'burn', 'poison', 'stun', 'sleep', 'confuse', 'lower_defense', 'lower_attack'],
    mechanics: ['guardian-intercept', 'transformation', 'skill-tree-passives', 'weapon-skills', 'rift-shift'],
    shipCombat: {
      autoMissileInterval: 3000,
      missileFlightTime: 800,
      defenseCapPercent: 60,
      shipTypes: {
        gunslinger: { ship: 'player/ship1', missile: 'plasma', color: '#f97316' },
        vanguard: { ship: 'player/ship2', missile: 'missile', color: '#ef4444' },
        technomancer: { ship: 'player/ship3', missile: 'torpedo', color: '#22d3ee' },
        riftwalker: { ship: 'player/ship1', missile: 'laser', color: '#a855f7' },
      },
    },
  },
};
